// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// CreateItemReader is a Reader for the CreateItem structure.
type CreateItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateItemCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateItemBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateItemCreated creates a CreateItemCreated with default headers values
func NewCreateItemCreated() *CreateItemCreated {
	return &CreateItemCreated{}
}

/*CreateItemCreated handles this case with default header values.

Category Created
*/
type CreateItemCreated struct {
	Payload *models.Item
}

func (o *CreateItemCreated) Error() string {
	return fmt.Sprintf("[POST /items][%d] createItemCreated  %+v", 201, o.Payload)
}

func (o *CreateItemCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Item)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateItemBadRequest creates a CreateItemBadRequest with default headers values
func NewCreateItemBadRequest() *CreateItemBadRequest {
	return &CreateItemBadRequest{}
}

/*CreateItemBadRequest handles this case with default header values.

Invalid input
*/
type CreateItemBadRequest struct {
}

func (o *CreateItemBadRequest) Error() string {
	return fmt.Sprintf("[POST /items][%d] createItemBadRequest ", 400)
}

func (o *CreateItemBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
