// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteItemsParams creates a new DeleteItemsParams object
// with the default values initialized.
func NewDeleteItemsParams() *DeleteItemsParams {

	return &DeleteItemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteItemsParamsWithTimeout creates a new DeleteItemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteItemsParamsWithTimeout(timeout time.Duration) *DeleteItemsParams {

	return &DeleteItemsParams{

		timeout: timeout,
	}
}

// NewDeleteItemsParamsWithContext creates a new DeleteItemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteItemsParamsWithContext(ctx context.Context) *DeleteItemsParams {

	return &DeleteItemsParams{

		Context: ctx,
	}
}

// NewDeleteItemsParamsWithHTTPClient creates a new DeleteItemsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteItemsParamsWithHTTPClient(client *http.Client) *DeleteItemsParams {

	return &DeleteItemsParams{
		HTTPClient: client,
	}
}

/*DeleteItemsParams contains all the parameters to send to the API endpoint
for the delete items operation typically these are written to a http.Request
*/
type DeleteItemsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete items params
func (o *DeleteItemsParams) WithTimeout(timeout time.Duration) *DeleteItemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete items params
func (o *DeleteItemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete items params
func (o *DeleteItemsParams) WithContext(ctx context.Context) *DeleteItemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete items params
func (o *DeleteItemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete items params
func (o *DeleteItemsParams) WithHTTPClient(client *http.Client) *DeleteItemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete items params
func (o *DeleteItemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteItemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
