// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetItemParams creates a new GetItemParams object
// with the default values initialized.
func NewGetItemParams() *GetItemParams {
	var ()
	return &GetItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetItemParamsWithTimeout creates a new GetItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetItemParamsWithTimeout(timeout time.Duration) *GetItemParams {
	var ()
	return &GetItemParams{

		timeout: timeout,
	}
}

// NewGetItemParamsWithContext creates a new GetItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetItemParamsWithContext(ctx context.Context) *GetItemParams {
	var ()
	return &GetItemParams{

		Context: ctx,
	}
}

// NewGetItemParamsWithHTTPClient creates a new GetItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetItemParamsWithHTTPClient(client *http.Client) *GetItemParams {
	var ()
	return &GetItemParams{
		HTTPClient: client,
	}
}

/*GetItemParams contains all the parameters to send to the API endpoint
for the get item operation typically these are written to a http.Request
*/
type GetItemParams struct {

	/*ID
	  Item ID

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get item params
func (o *GetItemParams) WithTimeout(timeout time.Duration) *GetItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get item params
func (o *GetItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get item params
func (o *GetItemParams) WithContext(ctx context.Context) *GetItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get item params
func (o *GetItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get item params
func (o *GetItemParams) WithHTTPClient(client *http.Client) *GetItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get item params
func (o *GetItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get item params
func (o *GetItemParams) WithID(id int64) *GetItemParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get item params
func (o *GetItemParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
