// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// GetItemsByOwnerReader is a Reader for the GetItemsByOwner structure.
type GetItemsByOwnerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetItemsByOwnerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetItemsByOwnerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetItemsByOwnerBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetItemsByOwnerNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetItemsByOwnerOK creates a GetItemsByOwnerOK with default headers values
func NewGetItemsByOwnerOK() *GetItemsByOwnerOK {
	return &GetItemsByOwnerOK{}
}

/*GetItemsByOwnerOK handles this case with default header values.

Status Ok
*/
type GetItemsByOwnerOK struct {
	Payload models.Items
}

func (o *GetItemsByOwnerOK) Error() string {
	return fmt.Sprintf("[GET /users/{id}/items][%d] getItemsByOwnerOK  %+v", 200, o.Payload)
}

func (o *GetItemsByOwnerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetItemsByOwnerBadRequest creates a GetItemsByOwnerBadRequest with default headers values
func NewGetItemsByOwnerBadRequest() *GetItemsByOwnerBadRequest {
	return &GetItemsByOwnerBadRequest{}
}

/*GetItemsByOwnerBadRequest handles this case with default header values.

Invalid input
*/
type GetItemsByOwnerBadRequest struct {
}

func (o *GetItemsByOwnerBadRequest) Error() string {
	return fmt.Sprintf("[GET /users/{id}/items][%d] getItemsByOwnerBadRequest ", 400)
}

func (o *GetItemsByOwnerBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetItemsByOwnerNotFound creates a GetItemsByOwnerNotFound with default headers values
func NewGetItemsByOwnerNotFound() *GetItemsByOwnerNotFound {
	return &GetItemsByOwnerNotFound{}
}

/*GetItemsByOwnerNotFound handles this case with default header values.

No items found
*/
type GetItemsByOwnerNotFound struct {
}

func (o *GetItemsByOwnerNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{id}/items][%d] getItemsByOwnerNotFound ", 404)
}

func (o *GetItemsByOwnerNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
