// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetItemsByOwnerParams creates a new GetItemsByOwnerParams object
// with the default values initialized.
func NewGetItemsByOwnerParams() *GetItemsByOwnerParams {
	var ()
	return &GetItemsByOwnerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetItemsByOwnerParamsWithTimeout creates a new GetItemsByOwnerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetItemsByOwnerParamsWithTimeout(timeout time.Duration) *GetItemsByOwnerParams {
	var ()
	return &GetItemsByOwnerParams{

		timeout: timeout,
	}
}

// NewGetItemsByOwnerParamsWithContext creates a new GetItemsByOwnerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetItemsByOwnerParamsWithContext(ctx context.Context) *GetItemsByOwnerParams {
	var ()
	return &GetItemsByOwnerParams{

		Context: ctx,
	}
}

// NewGetItemsByOwnerParamsWithHTTPClient creates a new GetItemsByOwnerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetItemsByOwnerParamsWithHTTPClient(client *http.Client) *GetItemsByOwnerParams {
	var ()
	return &GetItemsByOwnerParams{
		HTTPClient: client,
	}
}

/*GetItemsByOwnerParams contains all the parameters to send to the API endpoint
for the get items by owner operation typically these are written to a http.Request
*/
type GetItemsByOwnerParams struct {

	/*ID
	  Owner's ID

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get items by owner params
func (o *GetItemsByOwnerParams) WithTimeout(timeout time.Duration) *GetItemsByOwnerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get items by owner params
func (o *GetItemsByOwnerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get items by owner params
func (o *GetItemsByOwnerParams) WithContext(ctx context.Context) *GetItemsByOwnerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get items by owner params
func (o *GetItemsByOwnerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get items by owner params
func (o *GetItemsByOwnerParams) WithHTTPClient(client *http.Client) *GetItemsByOwnerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get items by owner params
func (o *GetItemsByOwnerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get items by owner params
func (o *GetItemsByOwnerParams) WithID(id int64) *GetItemsByOwnerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get items by owner params
func (o *GetItemsByOwnerParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetItemsByOwnerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
