// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// NewUpdateItemParams creates a new UpdateItemParams object
// with the default values initialized.
func NewUpdateItemParams() *UpdateItemParams {
	var ()
	return &UpdateItemParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateItemParamsWithTimeout creates a new UpdateItemParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateItemParamsWithTimeout(timeout time.Duration) *UpdateItemParams {
	var ()
	return &UpdateItemParams{

		timeout: timeout,
	}
}

// NewUpdateItemParamsWithContext creates a new UpdateItemParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateItemParamsWithContext(ctx context.Context) *UpdateItemParams {
	var ()
	return &UpdateItemParams{

		Context: ctx,
	}
}

// NewUpdateItemParamsWithHTTPClient creates a new UpdateItemParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateItemParamsWithHTTPClient(client *http.Client) *UpdateItemParams {
	var ()
	return &UpdateItemParams{
		HTTPClient: client,
	}
}

/*UpdateItemParams contains all the parameters to send to the API endpoint
for the update item operation typically these are written to a http.Request
*/
type UpdateItemParams struct {

	/*Body*/
	Body *models.Item
	/*ID
	  Item ID

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update item params
func (o *UpdateItemParams) WithTimeout(timeout time.Duration) *UpdateItemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update item params
func (o *UpdateItemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update item params
func (o *UpdateItemParams) WithContext(ctx context.Context) *UpdateItemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update item params
func (o *UpdateItemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update item params
func (o *UpdateItemParams) WithHTTPClient(client *http.Client) *UpdateItemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update item params
func (o *UpdateItemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update item params
func (o *UpdateItemParams) WithBody(body *models.Item) *UpdateItemParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update item params
func (o *UpdateItemParams) SetBody(body *models.Item) {
	o.Body = body
}

// WithID adds the id to the update item params
func (o *UpdateItemParams) WithID(id int64) *UpdateItemParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update item params
func (o *UpdateItemParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateItemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models.Item)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
