// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// NewCreateDescriptorParams creates a new CreateDescriptorParams object
// with the default values initialized.
func NewCreateDescriptorParams() *CreateDescriptorParams {
	var ()
	return &CreateDescriptorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDescriptorParamsWithTimeout creates a new CreateDescriptorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateDescriptorParamsWithTimeout(timeout time.Duration) *CreateDescriptorParams {
	var ()
	return &CreateDescriptorParams{

		timeout: timeout,
	}
}

// NewCreateDescriptorParamsWithContext creates a new CreateDescriptorParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateDescriptorParamsWithContext(ctx context.Context) *CreateDescriptorParams {
	var ()
	return &CreateDescriptorParams{

		Context: ctx,
	}
}

// NewCreateDescriptorParamsWithHTTPClient creates a new CreateDescriptorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateDescriptorParamsWithHTTPClient(client *http.Client) *CreateDescriptorParams {
	var ()
	return &CreateDescriptorParams{
		HTTPClient: client,
	}
}

/*CreateDescriptorParams contains all the parameters to send to the API endpoint
for the create descriptor operation typically these are written to a http.Request
*/
type CreateDescriptorParams struct {

	/*Body
	  a descriptor that will be updated

	*/
	Body *models.Descriptor

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create descriptor params
func (o *CreateDescriptorParams) WithTimeout(timeout time.Duration) *CreateDescriptorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create descriptor params
func (o *CreateDescriptorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create descriptor params
func (o *CreateDescriptorParams) WithContext(ctx context.Context) *CreateDescriptorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create descriptor params
func (o *CreateDescriptorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create descriptor params
func (o *CreateDescriptorParams) WithHTTPClient(client *http.Client) *CreateDescriptorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create descriptor params
func (o *CreateDescriptorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create descriptor params
func (o *CreateDescriptorParams) WithBody(body *models.Descriptor) *CreateDescriptorParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create descriptor params
func (o *CreateDescriptorParams) SetBody(body *models.Descriptor) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDescriptorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models.Descriptor)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
