// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// CreateDescriptorReader is a Reader for the CreateDescriptor structure.
type CreateDescriptorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDescriptorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateDescriptorCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateDescriptorBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewCreateDescriptorNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateDescriptorCreated creates a CreateDescriptorCreated with default headers values
func NewCreateDescriptorCreated() *CreateDescriptorCreated {
	return &CreateDescriptorCreated{}
}

/*CreateDescriptorCreated handles this case with default header values.

Descriptor Updated
*/
type CreateDescriptorCreated struct {
	Payload *models.Descriptor
}

func (o *CreateDescriptorCreated) Error() string {
	return fmt.Sprintf("[POST /descriptors][%d] createDescriptorCreated  %+v", 201, o.Payload)
}

func (o *CreateDescriptorCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Descriptor)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDescriptorBadRequest creates a CreateDescriptorBadRequest with default headers values
func NewCreateDescriptorBadRequest() *CreateDescriptorBadRequest {
	return &CreateDescriptorBadRequest{}
}

/*CreateDescriptorBadRequest handles this case with default header values.

Invalid input
*/
type CreateDescriptorBadRequest struct {
}

func (o *CreateDescriptorBadRequest) Error() string {
	return fmt.Sprintf("[POST /descriptors][%d] createDescriptorBadRequest ", 400)
}

func (o *CreateDescriptorBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDescriptorNotFound creates a CreateDescriptorNotFound with default headers values
func NewCreateDescriptorNotFound() *CreateDescriptorNotFound {
	return &CreateDescriptorNotFound{}
}

/*CreateDescriptorNotFound handles this case with default header values.

No items found
*/
type CreateDescriptorNotFound struct {
}

func (o *CreateDescriptorNotFound) Error() string {
	return fmt.Sprintf("[POST /descriptors][%d] createDescriptorNotFound ", 404)
}

func (o *CreateDescriptorNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
