// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// CreateDescriptorByDetailReader is a Reader for the CreateDescriptorByDetail structure.
type CreateDescriptorByDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDescriptorByDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateDescriptorByDetailCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateDescriptorByDetailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateDescriptorByDetailCreated creates a CreateDescriptorByDetailCreated with default headers values
func NewCreateDescriptorByDetailCreated() *CreateDescriptorByDetailCreated {
	return &CreateDescriptorByDetailCreated{}
}

/*CreateDescriptorByDetailCreated handles this case with default header values.

Descriptor Created
*/
type CreateDescriptorByDetailCreated struct {
	Payload *models.Descriptor
}

func (o *CreateDescriptorByDetailCreated) Error() string {
	return fmt.Sprintf("[POST /details/{id}/descriptors][%d] createDescriptorByDetailCreated  %+v", 201, o.Payload)
}

func (o *CreateDescriptorByDetailCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Descriptor)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDescriptorByDetailBadRequest creates a CreateDescriptorByDetailBadRequest with default headers values
func NewCreateDescriptorByDetailBadRequest() *CreateDescriptorByDetailBadRequest {
	return &CreateDescriptorByDetailBadRequest{}
}

/*CreateDescriptorByDetailBadRequest handles this case with default header values.

Invalid input
*/
type CreateDescriptorByDetailBadRequest struct {
}

func (o *CreateDescriptorByDetailBadRequest) Error() string {
	return fmt.Sprintf("[POST /details/{id}/descriptors][%d] createDescriptorByDetailBadRequest ", 400)
}

func (o *CreateDescriptorByDetailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
