// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// NewCreateDescriptorByDetailParams creates a new CreateDescriptorByDetailParams object
// with the default values initialized.
func NewCreateDescriptorByDetailParams() *CreateDescriptorByDetailParams {
	var ()
	return &CreateDescriptorByDetailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDescriptorByDetailParamsWithTimeout creates a new CreateDescriptorByDetailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateDescriptorByDetailParamsWithTimeout(timeout time.Duration) *CreateDescriptorByDetailParams {
	var ()
	return &CreateDescriptorByDetailParams{

		timeout: timeout,
	}
}

// NewCreateDescriptorByDetailParamsWithContext creates a new CreateDescriptorByDetailParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateDescriptorByDetailParamsWithContext(ctx context.Context) *CreateDescriptorByDetailParams {
	var ()
	return &CreateDescriptorByDetailParams{

		Context: ctx,
	}
}

// NewCreateDescriptorByDetailParamsWithHTTPClient creates a new CreateDescriptorByDetailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateDescriptorByDetailParamsWithHTTPClient(client *http.Client) *CreateDescriptorByDetailParams {
	var ()
	return &CreateDescriptorByDetailParams{
		HTTPClient: client,
	}
}

/*CreateDescriptorByDetailParams contains all the parameters to send to the API endpoint
for the create descriptor by detail operation typically these are written to a http.Request
*/
type CreateDescriptorByDetailParams struct {

	/*Body
	  Descriptor that will be created

	*/
	Body *models.Descriptor
	/*ID
	  Detail ID Associated with descriptor(s)

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) WithTimeout(timeout time.Duration) *CreateDescriptorByDetailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) WithContext(ctx context.Context) *CreateDescriptorByDetailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) WithHTTPClient(client *http.Client) *CreateDescriptorByDetailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) WithBody(body *models.Descriptor) *CreateDescriptorByDetailParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) SetBody(body *models.Descriptor) {
	o.Body = body
}

// WithID adds the id to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) WithID(id int64) *CreateDescriptorByDetailParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the create descriptor by detail params
func (o *CreateDescriptorByDetailParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDescriptorByDetailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models.Descriptor)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
