// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDescriptorParams creates a new DeleteDescriptorParams object
// with the default values initialized.
func NewDeleteDescriptorParams() *DeleteDescriptorParams {
	var ()
	return &DeleteDescriptorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDescriptorParamsWithTimeout creates a new DeleteDescriptorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDescriptorParamsWithTimeout(timeout time.Duration) *DeleteDescriptorParams {
	var ()
	return &DeleteDescriptorParams{

		timeout: timeout,
	}
}

// NewDeleteDescriptorParamsWithContext creates a new DeleteDescriptorParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDescriptorParamsWithContext(ctx context.Context) *DeleteDescriptorParams {
	var ()
	return &DeleteDescriptorParams{

		Context: ctx,
	}
}

// NewDeleteDescriptorParamsWithHTTPClient creates a new DeleteDescriptorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDescriptorParamsWithHTTPClient(client *http.Client) *DeleteDescriptorParams {
	var ()
	return &DeleteDescriptorParams{
		HTTPClient: client,
	}
}

/*DeleteDescriptorParams contains all the parameters to send to the API endpoint
for the delete descriptor operation typically these are written to a http.Request
*/
type DeleteDescriptorParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete descriptor params
func (o *DeleteDescriptorParams) WithTimeout(timeout time.Duration) *DeleteDescriptorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete descriptor params
func (o *DeleteDescriptorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete descriptor params
func (o *DeleteDescriptorParams) WithContext(ctx context.Context) *DeleteDescriptorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete descriptor params
func (o *DeleteDescriptorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete descriptor params
func (o *DeleteDescriptorParams) WithHTTPClient(client *http.Client) *DeleteDescriptorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete descriptor params
func (o *DeleteDescriptorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete descriptor params
func (o *DeleteDescriptorParams) WithID(id int64) *DeleteDescriptorParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete descriptor params
func (o *DeleteDescriptorParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDescriptorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
