// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteDescriptorsByDetailParams creates a new DeleteDescriptorsByDetailParams object
// with the default values initialized.
func NewDeleteDescriptorsByDetailParams() *DeleteDescriptorsByDetailParams {
	var ()
	return &DeleteDescriptorsByDetailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteDescriptorsByDetailParamsWithTimeout creates a new DeleteDescriptorsByDetailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteDescriptorsByDetailParamsWithTimeout(timeout time.Duration) *DeleteDescriptorsByDetailParams {
	var ()
	return &DeleteDescriptorsByDetailParams{

		timeout: timeout,
	}
}

// NewDeleteDescriptorsByDetailParamsWithContext creates a new DeleteDescriptorsByDetailParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteDescriptorsByDetailParamsWithContext(ctx context.Context) *DeleteDescriptorsByDetailParams {
	var ()
	return &DeleteDescriptorsByDetailParams{

		Context: ctx,
	}
}

// NewDeleteDescriptorsByDetailParamsWithHTTPClient creates a new DeleteDescriptorsByDetailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteDescriptorsByDetailParamsWithHTTPClient(client *http.Client) *DeleteDescriptorsByDetailParams {
	var ()
	return &DeleteDescriptorsByDetailParams{
		HTTPClient: client,
	}
}

/*DeleteDescriptorsByDetailParams contains all the parameters to send to the API endpoint
for the delete descriptors by detail operation typically these are written to a http.Request
*/
type DeleteDescriptorsByDetailParams struct {

	/*ID
	  Detail ID Associated with descriptor(s)

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete descriptors by detail params
func (o *DeleteDescriptorsByDetailParams) WithTimeout(timeout time.Duration) *DeleteDescriptorsByDetailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete descriptors by detail params
func (o *DeleteDescriptorsByDetailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete descriptors by detail params
func (o *DeleteDescriptorsByDetailParams) WithContext(ctx context.Context) *DeleteDescriptorsByDetailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete descriptors by detail params
func (o *DeleteDescriptorsByDetailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete descriptors by detail params
func (o *DeleteDescriptorsByDetailParams) WithHTTPClient(client *http.Client) *DeleteDescriptorsByDetailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete descriptors by detail params
func (o *DeleteDescriptorsByDetailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete descriptors by detail params
func (o *DeleteDescriptorsByDetailParams) WithID(id int64) *DeleteDescriptorsByDetailParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete descriptors by detail params
func (o *DeleteDescriptorsByDetailParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteDescriptorsByDetailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
