// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDescriptorParams creates a new GetDescriptorParams object
// with the default values initialized.
func NewGetDescriptorParams() *GetDescriptorParams {
	var ()
	return &GetDescriptorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDescriptorParamsWithTimeout creates a new GetDescriptorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDescriptorParamsWithTimeout(timeout time.Duration) *GetDescriptorParams {
	var ()
	return &GetDescriptorParams{

		timeout: timeout,
	}
}

// NewGetDescriptorParamsWithContext creates a new GetDescriptorParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDescriptorParamsWithContext(ctx context.Context) *GetDescriptorParams {
	var ()
	return &GetDescriptorParams{

		Context: ctx,
	}
}

// NewGetDescriptorParamsWithHTTPClient creates a new GetDescriptorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDescriptorParamsWithHTTPClient(client *http.Client) *GetDescriptorParams {
	var ()
	return &GetDescriptorParams{
		HTTPClient: client,
	}
}

/*GetDescriptorParams contains all the parameters to send to the API endpoint
for the get descriptor operation typically these are written to a http.Request
*/
type GetDescriptorParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get descriptor params
func (o *GetDescriptorParams) WithTimeout(timeout time.Duration) *GetDescriptorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get descriptor params
func (o *GetDescriptorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get descriptor params
func (o *GetDescriptorParams) WithContext(ctx context.Context) *GetDescriptorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get descriptor params
func (o *GetDescriptorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get descriptor params
func (o *GetDescriptorParams) WithHTTPClient(client *http.Client) *GetDescriptorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get descriptor params
func (o *GetDescriptorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get descriptor params
func (o *GetDescriptorParams) WithID(id int64) *GetDescriptorParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get descriptor params
func (o *GetDescriptorParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDescriptorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
