// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDescriptorsParams creates a new GetDescriptorsParams object
// with the default values initialized.
func NewGetDescriptorsParams() *GetDescriptorsParams {

	return &GetDescriptorsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDescriptorsParamsWithTimeout creates a new GetDescriptorsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDescriptorsParamsWithTimeout(timeout time.Duration) *GetDescriptorsParams {

	return &GetDescriptorsParams{

		timeout: timeout,
	}
}

// NewGetDescriptorsParamsWithContext creates a new GetDescriptorsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDescriptorsParamsWithContext(ctx context.Context) *GetDescriptorsParams {

	return &GetDescriptorsParams{

		Context: ctx,
	}
}

// NewGetDescriptorsParamsWithHTTPClient creates a new GetDescriptorsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDescriptorsParamsWithHTTPClient(client *http.Client) *GetDescriptorsParams {

	return &GetDescriptorsParams{
		HTTPClient: client,
	}
}

/*GetDescriptorsParams contains all the parameters to send to the API endpoint
for the get descriptors operation typically these are written to a http.Request
*/
type GetDescriptorsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get descriptors params
func (o *GetDescriptorsParams) WithTimeout(timeout time.Duration) *GetDescriptorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get descriptors params
func (o *GetDescriptorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get descriptors params
func (o *GetDescriptorsParams) WithContext(ctx context.Context) *GetDescriptorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get descriptors params
func (o *GetDescriptorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get descriptors params
func (o *GetDescriptorsParams) WithHTTPClient(client *http.Client) *GetDescriptorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get descriptors params
func (o *GetDescriptorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDescriptorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
