// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// GetDescriptorsByDetailReader is a Reader for the GetDescriptorsByDetail structure.
type GetDescriptorsByDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDescriptorsByDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDescriptorsByDetailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetDescriptorsByDetailNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDescriptorsByDetailOK creates a GetDescriptorsByDetailOK with default headers values
func NewGetDescriptorsByDetailOK() *GetDescriptorsByDetailOK {
	return &GetDescriptorsByDetailOK{}
}

/*GetDescriptorsByDetailOK handles this case with default header values.

Status Ok
*/
type GetDescriptorsByDetailOK struct {
	Payload *models.Description
}

func (o *GetDescriptorsByDetailOK) Error() string {
	return fmt.Sprintf("[GET /details/{id}/descriptors][%d] getDescriptorsByDetailOK  %+v", 200, o.Payload)
}

func (o *GetDescriptorsByDetailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Description)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDescriptorsByDetailNotFound creates a GetDescriptorsByDetailNotFound with default headers values
func NewGetDescriptorsByDetailNotFound() *GetDescriptorsByDetailNotFound {
	return &GetDescriptorsByDetailNotFound{}
}

/*GetDescriptorsByDetailNotFound handles this case with default header values.

No items found
*/
type GetDescriptorsByDetailNotFound struct {
}

func (o *GetDescriptorsByDetailNotFound) Error() string {
	return fmt.Sprintf("[GET /details/{id}/descriptors][%d] getDescriptorsByDetailNotFound ", 404)
}

func (o *GetDescriptorsByDetailNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
