// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// UpdateDescriptorReader is a Reader for the UpdateDescriptor structure.
type UpdateDescriptorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDescriptorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewUpdateDescriptorCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateDescriptorBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewUpdateDescriptorNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateDescriptorCreated creates a UpdateDescriptorCreated with default headers values
func NewUpdateDescriptorCreated() *UpdateDescriptorCreated {
	return &UpdateDescriptorCreated{}
}

/*UpdateDescriptorCreated handles this case with default header values.

Descriptor Updated
*/
type UpdateDescriptorCreated struct {
	Payload *models.Descriptor
}

func (o *UpdateDescriptorCreated) Error() string {
	return fmt.Sprintf("[PUT /Descriptors/{id}][%d] updateDescriptorCreated  %+v", 201, o.Payload)
}

func (o *UpdateDescriptorCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Descriptor)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDescriptorBadRequest creates a UpdateDescriptorBadRequest with default headers values
func NewUpdateDescriptorBadRequest() *UpdateDescriptorBadRequest {
	return &UpdateDescriptorBadRequest{}
}

/*UpdateDescriptorBadRequest handles this case with default header values.

Invalid input
*/
type UpdateDescriptorBadRequest struct {
}

func (o *UpdateDescriptorBadRequest) Error() string {
	return fmt.Sprintf("[PUT /Descriptors/{id}][%d] updateDescriptorBadRequest ", 400)
}

func (o *UpdateDescriptorBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateDescriptorNotFound creates a UpdateDescriptorNotFound with default headers values
func NewUpdateDescriptorNotFound() *UpdateDescriptorNotFound {
	return &UpdateDescriptorNotFound{}
}

/*UpdateDescriptorNotFound handles this case with default header values.

No items found
*/
type UpdateDescriptorNotFound struct {
}

func (o *UpdateDescriptorNotFound) Error() string {
	return fmt.Sprintf("[PUT /Descriptors/{id}][%d] updateDescriptorNotFound ", 404)
}

func (o *UpdateDescriptorNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
