// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// CreateSubCategoryReader is a Reader for the CreateSubCategory structure.
type CreateSubCategoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSubCategoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateSubCategoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateSubCategoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateSubCategoryCreated creates a CreateSubCategoryCreated with default headers values
func NewCreateSubCategoryCreated() *CreateSubCategoryCreated {
	return &CreateSubCategoryCreated{}
}

/*CreateSubCategoryCreated handles this case with default header values.

SubCategory Created
*/
type CreateSubCategoryCreated struct {
	Payload *models.SubCategory
}

func (o *CreateSubCategoryCreated) Error() string {
	return fmt.Sprintf("[POST /subcategories][%d] createSubCategoryCreated  %+v", 201, o.Payload)
}

func (o *CreateSubCategoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SubCategory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSubCategoryBadRequest creates a CreateSubCategoryBadRequest with default headers values
func NewCreateSubCategoryBadRequest() *CreateSubCategoryBadRequest {
	return &CreateSubCategoryBadRequest{}
}

/*CreateSubCategoryBadRequest handles this case with default header values.

Invalid input
*/
type CreateSubCategoryBadRequest struct {
}

func (o *CreateSubCategoryBadRequest) Error() string {
	return fmt.Sprintf("[POST /subcategories][%d] createSubCategoryBadRequest ", 400)
}

func (o *CreateSubCategoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
