// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// NewCreateSubCategoryParams creates a new CreateSubCategoryParams object
// with the default values initialized.
func NewCreateSubCategoryParams() *CreateSubCategoryParams {
	var ()
	return &CreateSubCategoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSubCategoryParamsWithTimeout creates a new CreateSubCategoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSubCategoryParamsWithTimeout(timeout time.Duration) *CreateSubCategoryParams {
	var ()
	return &CreateSubCategoryParams{

		timeout: timeout,
	}
}

// NewCreateSubCategoryParamsWithContext creates a new CreateSubCategoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSubCategoryParamsWithContext(ctx context.Context) *CreateSubCategoryParams {
	var ()
	return &CreateSubCategoryParams{

		Context: ctx,
	}
}

// NewCreateSubCategoryParamsWithHTTPClient creates a new CreateSubCategoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSubCategoryParamsWithHTTPClient(client *http.Client) *CreateSubCategoryParams {
	var ()
	return &CreateSubCategoryParams{
		HTTPClient: client,
	}
}

/*CreateSubCategoryParams contains all the parameters to send to the API endpoint
for the create sub category operation typically these are written to a http.Request
*/
type CreateSubCategoryParams struct {

	/*Body
	  Category that needs to be added to the DB

	*/
	Body *models.SubCategory

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create sub category params
func (o *CreateSubCategoryParams) WithTimeout(timeout time.Duration) *CreateSubCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create sub category params
func (o *CreateSubCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create sub category params
func (o *CreateSubCategoryParams) WithContext(ctx context.Context) *CreateSubCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create sub category params
func (o *CreateSubCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create sub category params
func (o *CreateSubCategoryParams) WithHTTPClient(client *http.Client) *CreateSubCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create sub category params
func (o *CreateSubCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create sub category params
func (o *CreateSubCategoryParams) WithBody(body *models.SubCategory) *CreateSubCategoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create sub category params
func (o *CreateSubCategoryParams) SetBody(body *models.SubCategory) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSubCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models.SubCategory)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
