// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSubCategoriesByCategoryReader is a Reader for the DeleteSubCategoriesByCategory structure.
type DeleteSubCategoriesByCategoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSubCategoriesByCategoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteSubCategoriesByCategoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteSubCategoriesByCategoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSubCategoriesByCategoryOK creates a DeleteSubCategoriesByCategoryOK with default headers values
func NewDeleteSubCategoriesByCategoryOK() *DeleteSubCategoriesByCategoryOK {
	return &DeleteSubCategoriesByCategoryOK{}
}

/*DeleteSubCategoriesByCategoryOK handles this case with default header values.

Status Ok
*/
type DeleteSubCategoriesByCategoryOK struct {
}

func (o *DeleteSubCategoriesByCategoryOK) Error() string {
	return fmt.Sprintf("[DELETE /catagories/{id}/subcategories][%d] deleteSubCategoriesByCategoryOK ", 200)
}

func (o *DeleteSubCategoriesByCategoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSubCategoriesByCategoryNotFound creates a DeleteSubCategoriesByCategoryNotFound with default headers values
func NewDeleteSubCategoriesByCategoryNotFound() *DeleteSubCategoriesByCategoryNotFound {
	return &DeleteSubCategoriesByCategoryNotFound{}
}

/*DeleteSubCategoriesByCategoryNotFound handles this case with default header values.

No items found
*/
type DeleteSubCategoriesByCategoryNotFound struct {
}

func (o *DeleteSubCategoriesByCategoryNotFound) Error() string {
	return fmt.Sprintf("[DELETE /catagories/{id}/subcategories][%d] deleteSubCategoriesByCategoryNotFound ", 404)
}

func (o *DeleteSubCategoriesByCategoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
