// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSubCategoriesParams creates a new DeleteSubCategoriesParams object
// with the default values initialized.
func NewDeleteSubCategoriesParams() *DeleteSubCategoriesParams {

	return &DeleteSubCategoriesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSubCategoriesParamsWithTimeout creates a new DeleteSubCategoriesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSubCategoriesParamsWithTimeout(timeout time.Duration) *DeleteSubCategoriesParams {

	return &DeleteSubCategoriesParams{

		timeout: timeout,
	}
}

// NewDeleteSubCategoriesParamsWithContext creates a new DeleteSubCategoriesParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSubCategoriesParamsWithContext(ctx context.Context) *DeleteSubCategoriesParams {

	return &DeleteSubCategoriesParams{

		Context: ctx,
	}
}

// NewDeleteSubCategoriesParamsWithHTTPClient creates a new DeleteSubCategoriesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSubCategoriesParamsWithHTTPClient(client *http.Client) *DeleteSubCategoriesParams {

	return &DeleteSubCategoriesParams{
		HTTPClient: client,
	}
}

/*DeleteSubCategoriesParams contains all the parameters to send to the API endpoint
for the delete sub categories operation typically these are written to a http.Request
*/
type DeleteSubCategoriesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete sub categories params
func (o *DeleteSubCategoriesParams) WithTimeout(timeout time.Duration) *DeleteSubCategoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete sub categories params
func (o *DeleteSubCategoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete sub categories params
func (o *DeleteSubCategoriesParams) WithContext(ctx context.Context) *DeleteSubCategoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete sub categories params
func (o *DeleteSubCategoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete sub categories params
func (o *DeleteSubCategoriesParams) WithHTTPClient(client *http.Client) *DeleteSubCategoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete sub categories params
func (o *DeleteSubCategoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSubCategoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
