// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSubCategoryParams creates a new DeleteSubCategoryParams object
// with the default values initialized.
func NewDeleteSubCategoryParams() *DeleteSubCategoryParams {
	var ()
	return &DeleteSubCategoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSubCategoryParamsWithTimeout creates a new DeleteSubCategoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSubCategoryParamsWithTimeout(timeout time.Duration) *DeleteSubCategoryParams {
	var ()
	return &DeleteSubCategoryParams{

		timeout: timeout,
	}
}

// NewDeleteSubCategoryParamsWithContext creates a new DeleteSubCategoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSubCategoryParamsWithContext(ctx context.Context) *DeleteSubCategoryParams {
	var ()
	return &DeleteSubCategoryParams{

		Context: ctx,
	}
}

// NewDeleteSubCategoryParamsWithHTTPClient creates a new DeleteSubCategoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSubCategoryParamsWithHTTPClient(client *http.Client) *DeleteSubCategoryParams {
	var ()
	return &DeleteSubCategoryParams{
		HTTPClient: client,
	}
}

/*DeleteSubCategoryParams contains all the parameters to send to the API endpoint
for the delete sub category operation typically these are written to a http.Request
*/
type DeleteSubCategoryParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete sub category params
func (o *DeleteSubCategoryParams) WithTimeout(timeout time.Duration) *DeleteSubCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete sub category params
func (o *DeleteSubCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete sub category params
func (o *DeleteSubCategoryParams) WithContext(ctx context.Context) *DeleteSubCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete sub category params
func (o *DeleteSubCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete sub category params
func (o *DeleteSubCategoryParams) WithHTTPClient(client *http.Client) *DeleteSubCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete sub category params
func (o *DeleteSubCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete sub category params
func (o *DeleteSubCategoryParams) WithID(id int64) *DeleteSubCategoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete sub category params
func (o *DeleteSubCategoryParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSubCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
