// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteSubCategoriesReader is a Reader for the DeleteSubCategories structure.
type DeleteSubCategoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSubCategoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteSubCategoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteSubCategoriesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteSubCategoriesOK creates a DeleteSubCategoriesOK with default headers values
func NewDeleteSubCategoriesOK() *DeleteSubCategoriesOK {
	return &DeleteSubCategoriesOK{}
}

/*DeleteSubCategoriesOK handles this case with default header values.

Status Ok
*/
type DeleteSubCategoriesOK struct {
}

func (o *DeleteSubCategoriesOK) Error() string {
	return fmt.Sprintf("[DELETE /subcategories][%d] deleteSubCategoriesOK ", 200)
}

func (o *DeleteSubCategoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSubCategoriesNotFound creates a DeleteSubCategoriesNotFound with default headers values
func NewDeleteSubCategoriesNotFound() *DeleteSubCategoriesNotFound {
	return &DeleteSubCategoriesNotFound{}
}

/*DeleteSubCategoriesNotFound handles this case with default header values.

No items found
*/
type DeleteSubCategoriesNotFound struct {
}

func (o *DeleteSubCategoriesNotFound) Error() string {
	return fmt.Sprintf("[DELETE /subcategories][%d] deleteSubCategoriesNotFound ", 404)
}

func (o *DeleteSubCategoriesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
