// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/test/models"
)

// GetSubCategoriesByCategoryReader is a Reader for the GetSubCategoriesByCategory structure.
type GetSubCategoriesByCategoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSubCategoriesByCategoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetSubCategoriesByCategoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetSubCategoriesByCategoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetSubCategoriesByCategoryOK creates a GetSubCategoriesByCategoryOK with default headers values
func NewGetSubCategoriesByCategoryOK() *GetSubCategoriesByCategoryOK {
	return &GetSubCategoriesByCategoryOK{}
}

/*GetSubCategoriesByCategoryOK handles this case with default header values.

Status Ok
*/
type GetSubCategoriesByCategoryOK struct {
	Payload models.SubCategories
}

func (o *GetSubCategoriesByCategoryOK) Error() string {
	return fmt.Sprintf("[GET /categories/{id}/subcategories][%d] getSubCategoriesByCategoryOK  %+v", 200, o.Payload)
}

func (o *GetSubCategoriesByCategoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetSubCategoriesByCategoryNotFound creates a GetSubCategoriesByCategoryNotFound with default headers values
func NewGetSubCategoriesByCategoryNotFound() *GetSubCategoriesByCategoryNotFound {
	return &GetSubCategoriesByCategoryNotFound{}
}

/*GetSubCategoriesByCategoryNotFound handles this case with default header values.

No items found
*/
type GetSubCategoriesByCategoryNotFound struct {
}

func (o *GetSubCategoriesByCategoryNotFound) Error() string {
	return fmt.Sprintf("[GET /categories/{id}/subcategories][%d] getSubCategoriesByCategoryNotFound ", 404)
}

func (o *GetSubCategoriesByCategoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
