// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSubCategoryParams creates a new GetSubCategoryParams object
// with the default values initialized.
func NewGetSubCategoryParams() *GetSubCategoryParams {
	var ()
	return &GetSubCategoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubCategoryParamsWithTimeout creates a new GetSubCategoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSubCategoryParamsWithTimeout(timeout time.Duration) *GetSubCategoryParams {
	var ()
	return &GetSubCategoryParams{

		timeout: timeout,
	}
}

// NewGetSubCategoryParamsWithContext creates a new GetSubCategoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSubCategoryParamsWithContext(ctx context.Context) *GetSubCategoryParams {
	var ()
	return &GetSubCategoryParams{

		Context: ctx,
	}
}

// NewGetSubCategoryParamsWithHTTPClient creates a new GetSubCategoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSubCategoryParamsWithHTTPClient(client *http.Client) *GetSubCategoryParams {
	var ()
	return &GetSubCategoryParams{
		HTTPClient: client,
	}
}

/*GetSubCategoryParams contains all the parameters to send to the API endpoint
for the get sub category operation typically these are written to a http.Request
*/
type GetSubCategoryParams struct {

	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sub category params
func (o *GetSubCategoryParams) WithTimeout(timeout time.Duration) *GetSubCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sub category params
func (o *GetSubCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sub category params
func (o *GetSubCategoryParams) WithContext(ctx context.Context) *GetSubCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sub category params
func (o *GetSubCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sub category params
func (o *GetSubCategoryParams) WithHTTPClient(client *http.Client) *GetSubCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sub category params
func (o *GetSubCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get sub category params
func (o *GetSubCategoryParams) WithID(id int64) *GetSubCategoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get sub category params
func (o *GetSubCategoryParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
