// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSubCategoriesByCategoryParams creates a new GetSubCategoriesByCategoryParams object
// with the default values initialized.
func NewGetSubCategoriesByCategoryParams() *GetSubCategoriesByCategoryParams {
	var ()
	return &GetSubCategoriesByCategoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubCategoriesByCategoryParamsWithTimeout creates a new GetSubCategoriesByCategoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSubCategoriesByCategoryParamsWithTimeout(timeout time.Duration) *GetSubCategoriesByCategoryParams {
	var ()
	return &GetSubCategoriesByCategoryParams{

		timeout: timeout,
	}
}

// NewGetSubCategoriesByCategoryParamsWithContext creates a new GetSubCategoriesByCategoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSubCategoriesByCategoryParamsWithContext(ctx context.Context) *GetSubCategoriesByCategoryParams {
	var ()
	return &GetSubCategoriesByCategoryParams{

		Context: ctx,
	}
}

// NewGetSubCategoriesByCategoryParamsWithHTTPClient creates a new GetSubCategoriesByCategoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSubCategoriesByCategoryParamsWithHTTPClient(client *http.Client) *GetSubCategoriesByCategoryParams {
	var ()
	return &GetSubCategoriesByCategoryParams{
		HTTPClient: client,
	}
}

/*GetSubCategoriesByCategoryParams contains all the parameters to send to the API endpoint
for the get sub categories by category operation typically these are written to a http.Request
*/
type GetSubCategoriesByCategoryParams struct {

	/*ID
	  Category ID Associated to Subcategory(s)

	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get sub categories by category params
func (o *GetSubCategoriesByCategoryParams) WithTimeout(timeout time.Duration) *GetSubCategoriesByCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get sub categories by category params
func (o *GetSubCategoriesByCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get sub categories by category params
func (o *GetSubCategoriesByCategoryParams) WithContext(ctx context.Context) *GetSubCategoriesByCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get sub categories by category params
func (o *GetSubCategoriesByCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get sub categories by category params
func (o *GetSubCategoriesByCategoryParams) WithHTTPClient(client *http.Client) *GetSubCategoriesByCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get sub categories by category params
func (o *GetSubCategoriesByCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get sub categories by category params
func (o *GetSubCategoriesByCategoryParams) WithID(id int64) *GetSubCategoriesByCategoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get sub categories by category params
func (o *GetSubCategoriesByCategoryParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubCategoriesByCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
