// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteCategoriesOKCode is the HTTP code returned for type DeleteCategoriesOK
const DeleteCategoriesOKCode int = 200

/*DeleteCategoriesOK Status Ok

swagger:response deleteCategoriesOK
*/
type DeleteCategoriesOK struct {
}

// NewDeleteCategoriesOK creates DeleteCategoriesOK with default headers values
func NewDeleteCategoriesOK() *DeleteCategoriesOK {
	return &DeleteCategoriesOK{}
}

// WriteResponse to the client
func (o *DeleteCategoriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteCategoriesNotFoundCode is the HTTP code returned for type DeleteCategoriesNotFound
const DeleteCategoriesNotFoundCode int = 404

/*DeleteCategoriesNotFound No items found

swagger:response deleteCategoriesNotFound
*/
type DeleteCategoriesNotFound struct {
}

// NewDeleteCategoriesNotFound creates DeleteCategoriesNotFound with default headers values
func NewDeleteCategoriesNotFound() *DeleteCategoriesNotFound {
	return &DeleteCategoriesNotFound{}
}

// WriteResponse to the client
func (o *DeleteCategoriesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
