// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteCategoryOKCode is the HTTP code returned for type DeleteCategoryOK
const DeleteCategoryOKCode int = 200

/*DeleteCategoryOK Status Ok

swagger:response deleteCategoryOK
*/
type DeleteCategoryOK struct {
}

// NewDeleteCategoryOK creates DeleteCategoryOK with default headers values
func NewDeleteCategoryOK() *DeleteCategoryOK {
	return &DeleteCategoryOK{}
}

// WriteResponse to the client
func (o *DeleteCategoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteCategoryBadRequestCode is the HTTP code returned for type DeleteCategoryBadRequest
const DeleteCategoryBadRequestCode int = 400

/*DeleteCategoryBadRequest Invalid input

swagger:response deleteCategoryBadRequest
*/
type DeleteCategoryBadRequest struct {
}

// NewDeleteCategoryBadRequest creates DeleteCategoryBadRequest with default headers values
func NewDeleteCategoryBadRequest() *DeleteCategoryBadRequest {
	return &DeleteCategoryBadRequest{}
}

// WriteResponse to the client
func (o *DeleteCategoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// DeleteCategoryNotFoundCode is the HTTP code returned for type DeleteCategoryNotFound
const DeleteCategoryNotFoundCode int = 404

/*DeleteCategoryNotFound No items found

swagger:response deleteCategoryNotFound
*/
type DeleteCategoryNotFound struct {
}

// NewDeleteCategoryNotFound creates DeleteCategoryNotFound with default headers values
func NewDeleteCategoryNotFound() *DeleteCategoryNotFound {
	return &DeleteCategoryNotFound{}
}

// WriteResponse to the client
func (o *DeleteCategoryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
