// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// GetCategoriesOKCode is the HTTP code returned for type GetCategoriesOK
const GetCategoriesOKCode int = 200

/*GetCategoriesOK Status Ok

swagger:response getCategoriesOK
*/
type GetCategoriesOK struct {

	/*
	  In: Body
	*/
	Payload models.Categories `json:"body,omitempty"`
}

// NewGetCategoriesOK creates GetCategoriesOK with default headers values
func NewGetCategoriesOK() *GetCategoriesOK {
	return &GetCategoriesOK{}
}

// WithPayload adds the payload to the get categories o k response
func (o *GetCategoriesOK) WithPayload(payload models.Categories) *GetCategoriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get categories o k response
func (o *GetCategoriesOK) SetPayload(payload models.Categories) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCategoriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Categories, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetCategoriesNotFoundCode is the HTTP code returned for type GetCategoriesNotFound
const GetCategoriesNotFoundCode int = 404

/*GetCategoriesNotFound No items found

swagger:response getCategoriesNotFound
*/
type GetCategoriesNotFound struct {
}

// NewGetCategoriesNotFound creates GetCategoriesNotFound with default headers values
func NewGetCategoriesNotFound() *GetCategoriesNotFound {
	return &GetCategoriesNotFound{}
}

// WriteResponse to the client
func (o *GetCategoriesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
