// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// UpdateCategoryCreatedCode is the HTTP code returned for type UpdateCategoryCreated
const UpdateCategoryCreatedCode int = 201

/*UpdateCategoryCreated Category Created

swagger:response updateCategoryCreated
*/
type UpdateCategoryCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Category `json:"body,omitempty"`
}

// NewUpdateCategoryCreated creates UpdateCategoryCreated with default headers values
func NewUpdateCategoryCreated() *UpdateCategoryCreated {
	return &UpdateCategoryCreated{}
}

// WithPayload adds the payload to the update category created response
func (o *UpdateCategoryCreated) WithPayload(payload *models.Category) *UpdateCategoryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update category created response
func (o *UpdateCategoryCreated) SetPayload(payload *models.Category) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCategoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateCategoryBadRequestCode is the HTTP code returned for type UpdateCategoryBadRequest
const UpdateCategoryBadRequestCode int = 400

/*UpdateCategoryBadRequest Invalid input

swagger:response updateCategoryBadRequest
*/
type UpdateCategoryBadRequest struct {
}

// NewUpdateCategoryBadRequest creates UpdateCategoryBadRequest with default headers values
func NewUpdateCategoryBadRequest() *UpdateCategoryBadRequest {
	return &UpdateCategoryBadRequest{}
}

// WriteResponse to the client
func (o *UpdateCategoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// UpdateCategoryNotFoundCode is the HTTP code returned for type UpdateCategoryNotFound
const UpdateCategoryNotFoundCode int = 404

/*UpdateCategoryNotFound No items found

swagger:response updateCategoryNotFound
*/
type UpdateCategoryNotFound struct {
}

// NewUpdateCategoryNotFound creates UpdateCategoryNotFound with default headers values
func NewUpdateCategoryNotFound() *UpdateCategoryNotFound {
	return &UpdateCategoryNotFound{}
}

// WriteResponse to the client
func (o *UpdateCategoryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
