// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteItemsByOwnerOKCode is the HTTP code returned for type DeleteItemsByOwnerOK
const DeleteItemsByOwnerOKCode int = 200

/*DeleteItemsByOwnerOK Status Ok

swagger:response deleteItemsByOwnerOK
*/
type DeleteItemsByOwnerOK struct {
}

// NewDeleteItemsByOwnerOK creates DeleteItemsByOwnerOK with default headers values
func NewDeleteItemsByOwnerOK() *DeleteItemsByOwnerOK {
	return &DeleteItemsByOwnerOK{}
}

// WriteResponse to the client
func (o *DeleteItemsByOwnerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
}

// DeleteItemsByOwnerNotFoundCode is the HTTP code returned for type DeleteItemsByOwnerNotFound
const DeleteItemsByOwnerNotFoundCode int = 404

/*DeleteItemsByOwnerNotFound No items found

swagger:response deleteItemsByOwnerNotFound
*/
type DeleteItemsByOwnerNotFound struct {
}

// NewDeleteItemsByOwnerNotFound creates DeleteItemsByOwnerNotFound with default headers values
func NewDeleteItemsByOwnerNotFound() *DeleteItemsByOwnerNotFound {
	return &DeleteItemsByOwnerNotFound{}
}

// WriteResponse to the client
func (o *DeleteItemsByOwnerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
