// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetItemsByOwnerHandlerFunc turns a function with the right signature into a get items by owner handler
type GetItemsByOwnerHandlerFunc func(GetItemsByOwnerParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetItemsByOwnerHandlerFunc) Handle(params GetItemsByOwnerParams) middleware.Responder {
	return fn(params)
}

// GetItemsByOwnerHandler interface for that can handle valid get items by owner params
type GetItemsByOwnerHandler interface {
	Handle(GetItemsByOwnerParams) middleware.Responder
}

// NewGetItemsByOwner creates a new http.Handler for the get items by owner operation
func NewGetItemsByOwner(ctx *middleware.Context, handler GetItemsByOwnerHandler) *GetItemsByOwner {
	return &GetItemsByOwner{Context: ctx, Handler: handler}
}

/*GetItemsByOwner swagger:route GET /users/{id}/items Items getItemsByOwner

Get all Items by Owner

*/
type GetItemsByOwner struct {
	Context *middleware.Context
	Handler GetItemsByOwnerHandler
}

func (o *GetItemsByOwner) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetItemsByOwnerParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
