// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// GetItemsOKCode is the HTTP code returned for type GetItemsOK
const GetItemsOKCode int = 200

/*GetItemsOK Status Ok

swagger:response getItemsOK
*/
type GetItemsOK struct {

	/*
	  In: Body
	*/
	Payload models.Items `json:"body,omitempty"`
}

// NewGetItemsOK creates GetItemsOK with default headers values
func NewGetItemsOK() *GetItemsOK {
	return &GetItemsOK{}
}

// WithPayload adds the payload to the get items o k response
func (o *GetItemsOK) WithPayload(payload models.Items) *GetItemsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get items o k response
func (o *GetItemsOK) SetPayload(payload models.Items) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Items, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetItemsNotFoundCode is the HTTP code returned for type GetItemsNotFound
const GetItemsNotFoundCode int = 404

/*GetItemsNotFound No items found

swagger:response getItemsNotFound
*/
type GetItemsNotFound struct {
}

// NewGetItemsNotFound creates GetItemsNotFound with default headers values
func NewGetItemsNotFound() *GetItemsNotFound {
	return &GetItemsNotFound{}
}

// WriteResponse to the client
func (o *GetItemsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
