// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetItemsBySubCategoryHandlerFunc turns a function with the right signature into a get items by sub category handler
type GetItemsBySubCategoryHandlerFunc func(GetItemsBySubCategoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetItemsBySubCategoryHandlerFunc) Handle(params GetItemsBySubCategoryParams) middleware.Responder {
	return fn(params)
}

// GetItemsBySubCategoryHandler interface for that can handle valid get items by sub category params
type GetItemsBySubCategoryHandler interface {
	Handle(GetItemsBySubCategoryParams) middleware.Responder
}

// NewGetItemsBySubCategory creates a new http.Handler for the get items by sub category operation
func NewGetItemsBySubCategory(ctx *middleware.Context, handler GetItemsBySubCategoryHandler) *GetItemsBySubCategory {
	return &GetItemsBySubCategory{Context: ctx, Handler: handler}
}

/*GetItemsBySubCategory swagger:route GET /subcategories/{id}/items Items getItemsBySubCategory

Get all Items by Subcategory

*/
type GetItemsBySubCategory struct {
	Context *middleware.Context
	Handler GetItemsBySubCategoryHandler
}

func (o *GetItemsBySubCategory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetItemsBySubCategoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
