// Code generated by go-swagger; DO NOT EDIT.

package items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// GetItemsByOwnerOKCode is the HTTP code returned for type GetItemsByOwnerOK
const GetItemsByOwnerOKCode int = 200

/*GetItemsByOwnerOK Status Ok

swagger:response getItemsByOwnerOK
*/
type GetItemsByOwnerOK struct {

	/*
	  In: Body
	*/
	Payload models.Items `json:"body,omitempty"`
}

// NewGetItemsByOwnerOK creates GetItemsByOwnerOK with default headers values
func NewGetItemsByOwnerOK() *GetItemsByOwnerOK {
	return &GetItemsByOwnerOK{}
}

// WithPayload adds the payload to the get items by owner o k response
func (o *GetItemsByOwnerOK) WithPayload(payload models.Items) *GetItemsByOwnerOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get items by owner o k response
func (o *GetItemsByOwnerOK) SetPayload(payload models.Items) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetItemsByOwnerOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Items, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetItemsByOwnerBadRequestCode is the HTTP code returned for type GetItemsByOwnerBadRequest
const GetItemsByOwnerBadRequestCode int = 400

/*GetItemsByOwnerBadRequest Invalid input

swagger:response getItemsByOwnerBadRequest
*/
type GetItemsByOwnerBadRequest struct {
}

// NewGetItemsByOwnerBadRequest creates GetItemsByOwnerBadRequest with default headers values
func NewGetItemsByOwnerBadRequest() *GetItemsByOwnerBadRequest {
	return &GetItemsByOwnerBadRequest{}
}

// WriteResponse to the client
func (o *GetItemsByOwnerBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// GetItemsByOwnerNotFoundCode is the HTTP code returned for type GetItemsByOwnerNotFound
const GetItemsByOwnerNotFoundCode int = 404

/*GetItemsByOwnerNotFound No items found

swagger:response getItemsByOwnerNotFound
*/
type GetItemsByOwnerNotFound struct {
}

// NewGetItemsByOwnerNotFound creates GetItemsByOwnerNotFound with default headers values
func NewGetItemsByOwnerNotFound() *GetItemsByOwnerNotFound {
	return &GetItemsByOwnerNotFound{}
}

// WriteResponse to the client
func (o *GetItemsByOwnerNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
