// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateDetailHandlerFunc turns a function with the right signature into a create detail handler
type CreateDetailHandlerFunc func(CreateDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateDetailHandlerFunc) Handle(params CreateDetailParams) middleware.Responder {
	return fn(params)
}

// CreateDetailHandler interface for that can handle valid create detail params
type CreateDetailHandler interface {
	Handle(CreateDetailParams) middleware.Responder
}

// NewCreateDetail creates a new http.Handler for the create detail operation
func NewCreateDetail(ctx *middleware.Context, handler CreateDetailHandler) *CreateDetail {
	return &CreateDetail{Context: ctx, Handler: handler}
}

/*CreateDetail swagger:route POST /details Details createDetail

Create a Detail

*/
type CreateDetail struct {
	Context *middleware.Context
	Handler CreateDetailHandler
}

func (o *CreateDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
