// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteDetailsHandlerFunc turns a function with the right signature into a delete details handler
type DeleteDetailsHandlerFunc func(DeleteDetailsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDetailsHandlerFunc) Handle(params DeleteDetailsParams) middleware.Responder {
	return fn(params)
}

// DeleteDetailsHandler interface for that can handle valid delete details params
type DeleteDetailsHandler interface {
	Handle(DeleteDetailsParams) middleware.Responder
}

// NewDeleteDetails creates a new http.Handler for the delete details operation
func NewDeleteDetails(ctx *middleware.Context, handler DeleteDetailsHandler) *DeleteDetails {
	return &DeleteDetails{Context: ctx, Handler: handler}
}

/*DeleteDetails swagger:route DELETE /details Details deleteDetails

Delete all Details

a details deletion will also remove all of its descriptors.

*/
type DeleteDetails struct {
	Context *middleware.Context
	Handler DeleteDetailsHandler
}

func (o *DeleteDetails) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteDetailsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
