// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteDetailHandlerFunc turns a function with the right signature into a delete detail handler
type DeleteDetailHandlerFunc func(DeleteDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteDetailHandlerFunc) Handle(params DeleteDetailParams) middleware.Responder {
	return fn(params)
}

// DeleteDetailHandler interface for that can handle valid delete detail params
type DeleteDetailHandler interface {
	Handle(DeleteDetailParams) middleware.Responder
}

// NewDeleteDetail creates a new http.Handler for the delete detail operation
func NewDeleteDetail(ctx *middleware.Context, handler DeleteDetailHandler) *DeleteDetail {
	return &DeleteDetail{Context: ctx, Handler: handler}
}

/*DeleteDetail swagger:route DELETE /details/{id} Details deleteDetail

Delete Detail

A detail deletion will also remove all of its descriptors.

*/
type DeleteDetail struct {
	Context *middleware.Context
	Handler DeleteDetailHandler
}

func (o *DeleteDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
