// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// GetDetailOKCode is the HTTP code returned for type GetDetailOK
const GetDetailOKCode int = 200

/*GetDetailOK Status Ok

swagger:response getDetailOK
*/
type GetDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.Detail `json:"body,omitempty"`
}

// NewGetDetailOK creates GetDetailOK with default headers values
func NewGetDetailOK() *GetDetailOK {
	return &GetDetailOK{}
}

// WithPayload adds the payload to the get detail o k response
func (o *GetDetailOK) WithPayload(payload *models.Detail) *GetDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get detail o k response
func (o *GetDetailOK) SetPayload(payload *models.Detail) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDetailBadRequestCode is the HTTP code returned for type GetDetailBadRequest
const GetDetailBadRequestCode int = 400

/*GetDetailBadRequest Invalid input

swagger:response getDetailBadRequest
*/
type GetDetailBadRequest struct {
}

// NewGetDetailBadRequest creates GetDetailBadRequest with default headers values
func NewGetDetailBadRequest() *GetDetailBadRequest {
	return &GetDetailBadRequest{}
}

// WriteResponse to the client
func (o *GetDetailBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// GetDetailNotFoundCode is the HTTP code returned for type GetDetailNotFound
const GetDetailNotFoundCode int = 404

/*GetDetailNotFound No items found

swagger:response getDetailNotFound
*/
type GetDetailNotFound struct {
}

// NewGetDetailNotFound creates GetDetailNotFound with default headers values
func NewGetDetailNotFound() *GetDetailNotFound {
	return &GetDetailNotFound{}
}

// WriteResponse to the client
func (o *GetDetailNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
