// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDetailHandlerFunc turns a function with the right signature into a get detail handler
type GetDetailHandlerFunc func(GetDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDetailHandlerFunc) Handle(params GetDetailParams) middleware.Responder {
	return fn(params)
}

// GetDetailHandler interface for that can handle valid get detail params
type GetDetailHandler interface {
	Handle(GetDetailParams) middleware.Responder
}

// NewGetDetail creates a new http.Handler for the get detail operation
func NewGetDetail(ctx *middleware.Context, handler GetDetailHandler) *GetDetail {
	return &GetDetail{Context: ctx, Handler: handler}
}

/*GetDetail swagger:route GET /details/{id} Details getDetail

Get a specific Detail

*/
type GetDetail struct {
	Context *middleware.Context
	Handler GetDetailHandler
}

func (o *GetDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
