// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// GetDetailsOKCode is the HTTP code returned for type GetDetailsOK
const GetDetailsOKCode int = 200

/*GetDetailsOK Status Ok

swagger:response getDetailsOK
*/
type GetDetailsOK struct {

	/*
	  In: Body
	*/
	Payload models.Details `json:"body,omitempty"`
}

// NewGetDetailsOK creates GetDetailsOK with default headers values
func NewGetDetailsOK() *GetDetailsOK {
	return &GetDetailsOK{}
}

// WithPayload adds the payload to the get details o k response
func (o *GetDetailsOK) WithPayload(payload models.Details) *GetDetailsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get details o k response
func (o *GetDetailsOK) SetPayload(payload models.Details) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDetailsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Details, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetDetailsNotFoundCode is the HTTP code returned for type GetDetailsNotFound
const GetDetailsNotFoundCode int = 404

/*GetDetailsNotFound No items found

swagger:response getDetailsNotFound
*/
type GetDetailsNotFound struct {
}

// NewGetDetailsNotFound creates GetDetailsNotFound with default headers values
func NewGetDetailsNotFound() *GetDetailsNotFound {
	return &GetDetailsNotFound{}
}

// WriteResponse to the client
func (o *GetDetailsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
