// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateDetailHandlerFunc turns a function with the right signature into a update detail handler
type UpdateDetailHandlerFunc func(UpdateDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateDetailHandlerFunc) Handle(params UpdateDetailParams) middleware.Responder {
	return fn(params)
}

// UpdateDetailHandler interface for that can handle valid update detail params
type UpdateDetailHandler interface {
	Handle(UpdateDetailParams) middleware.Responder
}

// NewUpdateDetail creates a new http.Handler for the update detail operation
func NewUpdateDetail(ctx *middleware.Context, handler UpdateDetailHandler) *UpdateDetail {
	return &UpdateDetail{Context: ctx, Handler: handler}
}

/*UpdateDetail swagger:route PUT /details/{id} Details updateDetail

Update a specific Detail

*/
type UpdateDetail struct {
	Context *middleware.Context
	Handler UpdateDetailHandler
}

func (o *UpdateDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
