// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateDescriptorHandlerFunc turns a function with the right signature into a create descriptor handler
type CreateDescriptorHandlerFunc func(CreateDescriptorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateDescriptorHandlerFunc) Handle(params CreateDescriptorParams) middleware.Responder {
	return fn(params)
}

// CreateDescriptorHandler interface for that can handle valid create descriptor params
type CreateDescriptorHandler interface {
	Handle(CreateDescriptorParams) middleware.Responder
}

// NewCreateDescriptor creates a new http.Handler for the create descriptor operation
func NewCreateDescriptor(ctx *middleware.Context, handler CreateDescriptorHandler) *CreateDescriptor {
	return &CreateDescriptor{Context: ctx, Handler: handler}
}

/*CreateDescriptor swagger:route POST /descriptors Descriptors createDescriptor

Create a  Descriptor

*/
type CreateDescriptor struct {
	Context *middleware.Context
	Handler CreateDescriptorHandler
}

func (o *CreateDescriptor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateDescriptorParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
