// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// CreateDescriptorCreatedCode is the HTTP code returned for type CreateDescriptorCreated
const CreateDescriptorCreatedCode int = 201

/*CreateDescriptorCreated Descriptor Updated

swagger:response createDescriptorCreated
*/
type CreateDescriptorCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Descriptor `json:"body,omitempty"`
}

// NewCreateDescriptorCreated creates CreateDescriptorCreated with default headers values
func NewCreateDescriptorCreated() *CreateDescriptorCreated {
	return &CreateDescriptorCreated{}
}

// WithPayload adds the payload to the create descriptor created response
func (o *CreateDescriptorCreated) WithPayload(payload *models.Descriptor) *CreateDescriptorCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create descriptor created response
func (o *CreateDescriptorCreated) SetPayload(payload *models.Descriptor) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateDescriptorCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateDescriptorBadRequestCode is the HTTP code returned for type CreateDescriptorBadRequest
const CreateDescriptorBadRequestCode int = 400

/*CreateDescriptorBadRequest Invalid input

swagger:response createDescriptorBadRequest
*/
type CreateDescriptorBadRequest struct {
}

// NewCreateDescriptorBadRequest creates CreateDescriptorBadRequest with default headers values
func NewCreateDescriptorBadRequest() *CreateDescriptorBadRequest {
	return &CreateDescriptorBadRequest{}
}

// WriteResponse to the client
func (o *CreateDescriptorBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// CreateDescriptorNotFoundCode is the HTTP code returned for type CreateDescriptorNotFound
const CreateDescriptorNotFoundCode int = 404

/*CreateDescriptorNotFound No items found

swagger:response createDescriptorNotFound
*/
type CreateDescriptorNotFound struct {
}

// NewCreateDescriptorNotFound creates CreateDescriptorNotFound with default headers values
func NewCreateDescriptorNotFound() *CreateDescriptorNotFound {
	return &CreateDescriptorNotFound{}
}

// WriteResponse to the client
func (o *CreateDescriptorNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
