// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetDescriptorsByDetailHandlerFunc turns a function with the right signature into a get descriptors by detail handler
type GetDescriptorsByDetailHandlerFunc func(GetDescriptorsByDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetDescriptorsByDetailHandlerFunc) Handle(params GetDescriptorsByDetailParams) middleware.Responder {
	return fn(params)
}

// GetDescriptorsByDetailHandler interface for that can handle valid get descriptors by detail params
type GetDescriptorsByDetailHandler interface {
	Handle(GetDescriptorsByDetailParams) middleware.Responder
}

// NewGetDescriptorsByDetail creates a new http.Handler for the get descriptors by detail operation
func NewGetDescriptorsByDetail(ctx *middleware.Context, handler GetDescriptorsByDetailHandler) *GetDescriptorsByDetail {
	return &GetDescriptorsByDetail{Context: ctx, Handler: handler}
}

/*GetDescriptorsByDetail swagger:route GET /details/{id}/descriptors Descriptors getDescriptorsByDetail

Get all Descriptors by Detail

*/
type GetDescriptorsByDetail struct {
	Context *middleware.Context
	Handler GetDescriptorsByDetailHandler
}

func (o *GetDescriptorsByDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetDescriptorsByDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
