// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// GetDescriptorsByDetailOKCode is the HTTP code returned for type GetDescriptorsByDetailOK
const GetDescriptorsByDetailOKCode int = 200

/*GetDescriptorsByDetailOK Status Ok

swagger:response getDescriptorsByDetailOK
*/
type GetDescriptorsByDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.Description `json:"body,omitempty"`
}

// NewGetDescriptorsByDetailOK creates GetDescriptorsByDetailOK with default headers values
func NewGetDescriptorsByDetailOK() *GetDescriptorsByDetailOK {
	return &GetDescriptorsByDetailOK{}
}

// WithPayload adds the payload to the get descriptors by detail o k response
func (o *GetDescriptorsByDetailOK) WithPayload(payload *models.Description) *GetDescriptorsByDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get descriptors by detail o k response
func (o *GetDescriptorsByDetailOK) SetPayload(payload *models.Description) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDescriptorsByDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetDescriptorsByDetailNotFoundCode is the HTTP code returned for type GetDescriptorsByDetailNotFound
const GetDescriptorsByDetailNotFoundCode int = 404

/*GetDescriptorsByDetailNotFound No items found

swagger:response getDescriptorsByDetailNotFound
*/
type GetDescriptorsByDetailNotFound struct {
}

// NewGetDescriptorsByDetailNotFound creates GetDescriptorsByDetailNotFound with default headers values
func NewGetDescriptorsByDetailNotFound() *GetDescriptorsByDetailNotFound {
	return &GetDescriptorsByDetailNotFound{}
}

// WriteResponse to the client
func (o *GetDescriptorsByDetailNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
