// Code generated by go-swagger; DO NOT EDIT.

package descriptors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// UpdateDescriptorCreatedCode is the HTTP code returned for type UpdateDescriptorCreated
const UpdateDescriptorCreatedCode int = 201

/*UpdateDescriptorCreated Descriptor Updated

swagger:response updateDescriptorCreated
*/
type UpdateDescriptorCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Descriptor `json:"body,omitempty"`
}

// NewUpdateDescriptorCreated creates UpdateDescriptorCreated with default headers values
func NewUpdateDescriptorCreated() *UpdateDescriptorCreated {
	return &UpdateDescriptorCreated{}
}

// WithPayload adds the payload to the update descriptor created response
func (o *UpdateDescriptorCreated) WithPayload(payload *models.Descriptor) *UpdateDescriptorCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update descriptor created response
func (o *UpdateDescriptorCreated) SetPayload(payload *models.Descriptor) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateDescriptorCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateDescriptorBadRequestCode is the HTTP code returned for type UpdateDescriptorBadRequest
const UpdateDescriptorBadRequestCode int = 400

/*UpdateDescriptorBadRequest Invalid input

swagger:response updateDescriptorBadRequest
*/
type UpdateDescriptorBadRequest struct {
}

// NewUpdateDescriptorBadRequest creates UpdateDescriptorBadRequest with default headers values
func NewUpdateDescriptorBadRequest() *UpdateDescriptorBadRequest {
	return &UpdateDescriptorBadRequest{}
}

// WriteResponse to the client
func (o *UpdateDescriptorBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// UpdateDescriptorNotFoundCode is the HTTP code returned for type UpdateDescriptorNotFound
const UpdateDescriptorNotFoundCode int = 404

/*UpdateDescriptorNotFound No items found

swagger:response updateDescriptorNotFound
*/
type UpdateDescriptorNotFound struct {
}

// NewUpdateDescriptorNotFound creates UpdateDescriptorNotFound with default headers values
func NewUpdateDescriptorNotFound() *UpdateDescriptorNotFound {
	return &UpdateDescriptorNotFound{}
}

// WriteResponse to the client
func (o *UpdateDescriptorNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
