// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteCategoryReader is a Reader for the DeleteCategory structure.
type DeleteCategoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCategoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteCategoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteCategoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteCategoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCategoryOK creates a DeleteCategoryOK with default headers values
func NewDeleteCategoryOK() *DeleteCategoryOK {
	return &DeleteCategoryOK{}
}

/*DeleteCategoryOK handles this case with default header values.

Status Ok
*/
type DeleteCategoryOK struct {
}

func (o *DeleteCategoryOK) Error() string {
	return fmt.Sprintf("[DELETE /categories/{id}][%d] deleteCategoryOK ", 200)
}

func (o *DeleteCategoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCategoryBadRequest creates a DeleteCategoryBadRequest with default headers values
func NewDeleteCategoryBadRequest() *DeleteCategoryBadRequest {
	return &DeleteCategoryBadRequest{}
}

/*DeleteCategoryBadRequest handles this case with default header values.

Invalid input
*/
type DeleteCategoryBadRequest struct {
}

func (o *DeleteCategoryBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /categories/{id}][%d] deleteCategoryBadRequest ", 400)
}

func (o *DeleteCategoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteCategoryNotFound creates a DeleteCategoryNotFound with default headers values
func NewDeleteCategoryNotFound() *DeleteCategoryNotFound {
	return &DeleteCategoryNotFound{}
}

/*DeleteCategoryNotFound handles this case with default header values.

No items found
*/
type DeleteCategoryNotFound struct {
}

func (o *DeleteCategoryNotFound) Error() string {
	return fmt.Sprintf("[DELETE /categories/{id}][%d] deleteCategoryNotFound ", 404)
}

func (o *DeleteCategoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
