// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// NewUpdateCategoryParams creates a new UpdateCategoryParams object
// with the default values initialized.
func NewUpdateCategoryParams() *UpdateCategoryParams {
	var ()
	return &UpdateCategoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCategoryParamsWithTimeout creates a new UpdateCategoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCategoryParamsWithTimeout(timeout time.Duration) *UpdateCategoryParams {
	var ()
	return &UpdateCategoryParams{

		timeout: timeout,
	}
}

// NewUpdateCategoryParamsWithContext creates a new UpdateCategoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCategoryParamsWithContext(ctx context.Context) *UpdateCategoryParams {
	var ()
	return &UpdateCategoryParams{

		Context: ctx,
	}
}

// NewUpdateCategoryParamsWithHTTPClient creates a new UpdateCategoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCategoryParamsWithHTTPClient(client *http.Client) *UpdateCategoryParams {
	var ()
	return &UpdateCategoryParams{
		HTTPClient: client,
	}
}

/*UpdateCategoryParams contains all the parameters to send to the API endpoint
for the update category operation typically these are written to a http.Request
*/
type UpdateCategoryParams struct {

	/*Body
	  a category that needs to be updated

	*/
	Body *models.Category
	/*ID*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update category params
func (o *UpdateCategoryParams) WithTimeout(timeout time.Duration) *UpdateCategoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update category params
func (o *UpdateCategoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update category params
func (o *UpdateCategoryParams) WithContext(ctx context.Context) *UpdateCategoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update category params
func (o *UpdateCategoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update category params
func (o *UpdateCategoryParams) WithHTTPClient(client *http.Client) *UpdateCategoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update category params
func (o *UpdateCategoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update category params
func (o *UpdateCategoryParams) WithBody(body *models.Category) *UpdateCategoryParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update category params
func (o *UpdateCategoryParams) SetBody(body *models.Category) {
	o.Body = body
}

// WithID adds the id to the update category params
func (o *UpdateCategoryParams) WithID(id int64) *UpdateCategoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update category params
func (o *UpdateCategoryParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCategoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models.Category)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
