// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// UpdateCategoryReader is a Reader for the UpdateCategory structure.
type UpdateCategoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateCategoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewUpdateCategoryCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateCategoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewUpdateCategoryNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateCategoryCreated creates a UpdateCategoryCreated with default headers values
func NewUpdateCategoryCreated() *UpdateCategoryCreated {
	return &UpdateCategoryCreated{}
}

/*UpdateCategoryCreated handles this case with default header values.

Category Created
*/
type UpdateCategoryCreated struct {
	Payload *models.Category
}

func (o *UpdateCategoryCreated) Error() string {
	return fmt.Sprintf("[PUT /categories/{id}][%d] updateCategoryCreated  %+v", 201, o.Payload)
}

func (o *UpdateCategoryCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Category)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateCategoryBadRequest creates a UpdateCategoryBadRequest with default headers values
func NewUpdateCategoryBadRequest() *UpdateCategoryBadRequest {
	return &UpdateCategoryBadRequest{}
}

/*UpdateCategoryBadRequest handles this case with default header values.

Invalid input
*/
type UpdateCategoryBadRequest struct {
}

func (o *UpdateCategoryBadRequest) Error() string {
	return fmt.Sprintf("[PUT /categories/{id}][%d] updateCategoryBadRequest ", 400)
}

func (o *UpdateCategoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateCategoryNotFound creates a UpdateCategoryNotFound with default headers values
func NewUpdateCategoryNotFound() *UpdateCategoryNotFound {
	return &UpdateCategoryNotFound{}
}

/*UpdateCategoryNotFound handles this case with default header values.

No items found
*/
type UpdateCategoryNotFound struct {
}

func (o *UpdateCategoryNotFound) Error() string {
	return fmt.Sprintf("[PUT /categories/{id}][%d] updateCategoryNotFound ", 404)
}

func (o *UpdateCategoryNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
