// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// CreateSubCategoryByCategoryCreatedCode is the HTTP code returned for type CreateSubCategoryByCategoryCreated
const CreateSubCategoryByCategoryCreatedCode int = 201

/*CreateSubCategoryByCategoryCreated SubCategory Created

swagger:response createSubCategoryByCategoryCreated
*/
type CreateSubCategoryByCategoryCreated struct {

	/*
	  In: Body
	*/
	Payload *models.SubCategory `json:"body,omitempty"`
}

// NewCreateSubCategoryByCategoryCreated creates CreateSubCategoryByCategoryCreated with default headers values
func NewCreateSubCategoryByCategoryCreated() *CreateSubCategoryByCategoryCreated {
	return &CreateSubCategoryByCategoryCreated{}
}

// WithPayload adds the payload to the create sub category by category created response
func (o *CreateSubCategoryByCategoryCreated) WithPayload(payload *models.SubCategory) *CreateSubCategoryByCategoryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create sub category by category created response
func (o *CreateSubCategoryByCategoryCreated) SetPayload(payload *models.SubCategory) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSubCategoryByCategoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSubCategoryByCategoryBadRequestCode is the HTTP code returned for type CreateSubCategoryByCategoryBadRequest
const CreateSubCategoryByCategoryBadRequestCode int = 400

/*CreateSubCategoryByCategoryBadRequest Invalid input

swagger:response createSubCategoryByCategoryBadRequest
*/
type CreateSubCategoryByCategoryBadRequest struct {
}

// NewCreateSubCategoryByCategoryBadRequest creates CreateSubCategoryByCategoryBadRequest with default headers values
func NewCreateSubCategoryByCategoryBadRequest() *CreateSubCategoryByCategoryBadRequest {
	return &CreateSubCategoryByCategoryBadRequest{}
}

// WriteResponse to the client
func (o *CreateSubCategoryByCategoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
