// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// CreateSubCategoryCreatedCode is the HTTP code returned for type CreateSubCategoryCreated
const CreateSubCategoryCreatedCode int = 201

/*CreateSubCategoryCreated SubCategory Created

swagger:response createSubCategoryCreated
*/
type CreateSubCategoryCreated struct {

	/*
	  In: Body
	*/
	Payload *models.SubCategory `json:"body,omitempty"`
}

// NewCreateSubCategoryCreated creates CreateSubCategoryCreated with default headers values
func NewCreateSubCategoryCreated() *CreateSubCategoryCreated {
	return &CreateSubCategoryCreated{}
}

// WithPayload adds the payload to the create sub category created response
func (o *CreateSubCategoryCreated) WithPayload(payload *models.SubCategory) *CreateSubCategoryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create sub category created response
func (o *CreateSubCategoryCreated) SetPayload(payload *models.SubCategory) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateSubCategoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateSubCategoryBadRequestCode is the HTTP code returned for type CreateSubCategoryBadRequest
const CreateSubCategoryBadRequestCode int = 400

/*CreateSubCategoryBadRequest Invalid input

swagger:response createSubCategoryBadRequest
*/
type CreateSubCategoryBadRequest struct {
}

// NewCreateSubCategoryBadRequest creates CreateSubCategoryBadRequest with default headers values
func NewCreateSubCategoryBadRequest() *CreateSubCategoryBadRequest {
	return &CreateSubCategoryBadRequest{}
}

// WriteResponse to the client
func (o *CreateSubCategoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}
