// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteSubCategoryHandlerFunc turns a function with the right signature into a delete sub category handler
type DeleteSubCategoryHandlerFunc func(DeleteSubCategoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSubCategoryHandlerFunc) Handle(params DeleteSubCategoryParams) middleware.Responder {
	return fn(params)
}

// DeleteSubCategoryHandler interface for that can handle valid delete sub category params
type DeleteSubCategoryHandler interface {
	Handle(DeleteSubCategoryParams) middleware.Responder
}

// NewDeleteSubCategory creates a new http.Handler for the delete sub category operation
func NewDeleteSubCategory(ctx *middleware.Context, handler DeleteSubCategoryHandler) *DeleteSubCategory {
	return &DeleteSubCategory{Context: ctx, Handler: handler}
}

/*DeleteSubCategory swagger:route DELETE /subcategories/{id} Subcategories deleteSubCategory

Delete a specific SubCategory

removes a specfic subcategory.

*/
type DeleteSubCategory struct {
	Context *middleware.Context
	Handler DeleteSubCategoryHandler
}

func (o *DeleteSubCategory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteSubCategoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
