// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteSubCategoriesHandlerFunc turns a function with the right signature into a delete sub categories handler
type DeleteSubCategoriesHandlerFunc func(DeleteSubCategoriesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSubCategoriesHandlerFunc) Handle(params DeleteSubCategoriesParams) middleware.Responder {
	return fn(params)
}

// DeleteSubCategoriesHandler interface for that can handle valid delete sub categories params
type DeleteSubCategoriesHandler interface {
	Handle(DeleteSubCategoriesParams) middleware.Responder
}

// NewDeleteSubCategories creates a new http.Handler for the delete sub categories operation
func NewDeleteSubCategories(ctx *middleware.Context, handler DeleteSubCategoriesHandler) *DeleteSubCategories {
	return &DeleteSubCategories{Context: ctx, Handler: handler}
}

/*DeleteSubCategories swagger:route DELETE /subcategories Subcategories deleteSubCategories

Delete all SubCategories

removes all subcategories.

*/
type DeleteSubCategories struct {
	Context *middleware.Context
	Handler DeleteSubCategoriesHandler
}

func (o *DeleteSubCategories) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteSubCategoriesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
