// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSubCategoriesByCategoryHandlerFunc turns a function with the right signature into a get sub categories by category handler
type GetSubCategoriesByCategoryHandlerFunc func(GetSubCategoriesByCategoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSubCategoriesByCategoryHandlerFunc) Handle(params GetSubCategoriesByCategoryParams) middleware.Responder {
	return fn(params)
}

// GetSubCategoriesByCategoryHandler interface for that can handle valid get sub categories by category params
type GetSubCategoriesByCategoryHandler interface {
	Handle(GetSubCategoriesByCategoryParams) middleware.Responder
}

// NewGetSubCategoriesByCategory creates a new http.Handler for the get sub categories by category operation
func NewGetSubCategoriesByCategory(ctx *middleware.Context, handler GetSubCategoriesByCategoryHandler) *GetSubCategoriesByCategory {
	return &GetSubCategoriesByCategory{Context: ctx, Handler: handler}
}

/*GetSubCategoriesByCategory swagger:route GET /catagories/{id}/subcategories Subcategories getSubCategoriesByCategory

Get all SubCategories by Category

*/
type GetSubCategoriesByCategory struct {
	Context *middleware.Context
	Handler GetSubCategoriesByCategoryHandler
}

func (o *GetSubCategoriesByCategory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSubCategoriesByCategoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
