// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// GetSubCategoryOKCode is the HTTP code returned for type GetSubCategoryOK
const GetSubCategoryOKCode int = 200

/*GetSubCategoryOK Status Ok

swagger:response getSubCategoryOK
*/
type GetSubCategoryOK struct {

	/*
	  In: Body
	*/
	Payload *models.SubCategory `json:"body,omitempty"`
}

// NewGetSubCategoryOK creates GetSubCategoryOK with default headers values
func NewGetSubCategoryOK() *GetSubCategoryOK {
	return &GetSubCategoryOK{}
}

// WithPayload adds the payload to the get sub category o k response
func (o *GetSubCategoryOK) WithPayload(payload *models.SubCategory) *GetSubCategoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sub category o k response
func (o *GetSubCategoryOK) SetPayload(payload *models.SubCategory) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSubCategoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Set("Access-Control-Allow-Origin", "*")
	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSubCategoryBadRequestCode is the HTTP code returned for type GetSubCategoryBadRequest
const GetSubCategoryBadRequestCode int = 400

/*GetSubCategoryBadRequest Invalid input

swagger:response getSubCategoryBadRequest
*/
type GetSubCategoryBadRequest struct {
}

// NewGetSubCategoryBadRequest creates GetSubCategoryBadRequest with default headers values
func NewGetSubCategoryBadRequest() *GetSubCategoryBadRequest {
	return &GetSubCategoryBadRequest{}
}

// WriteResponse to the client
func (o *GetSubCategoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// GetSubCategoryNotFoundCode is the HTTP code returned for type GetSubCategoryNotFound
const GetSubCategoryNotFoundCode int = 404

/*GetSubCategoryNotFound No items found

swagger:response getSubCategoryNotFound
*/
type GetSubCategoryNotFound struct {
}

// NewGetSubCategoryNotFound creates GetSubCategoryNotFound with default headers values
func NewGetSubCategoryNotFound() *GetSubCategoryNotFound {
	return &GetSubCategoryNotFound{}
}

// WriteResponse to the client
func (o *GetSubCategoryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Set("Access-Control-Allow-Origin", "*")
	rw.WriteHeader(404)
}
