// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// GetSubCategoriesOKCode is the HTTP code returned for type GetSubCategoriesOK
const GetSubCategoriesOKCode int = 200

/*GetSubCategoriesOK Status Ok

swagger:response getSubCategoriesOK
*/
type GetSubCategoriesOK struct {

	/*
	  In: Body
	*/
	Payload models.SubCategories `json:"body,omitempty"`
}

// NewGetSubCategoriesOK creates GetSubCategoriesOK with default headers values
func NewGetSubCategoriesOK() *GetSubCategoriesOK {
	return &GetSubCategoriesOK{}
}

// WithPayload adds the payload to the get sub categories o k response
func (o *GetSubCategoriesOK) WithPayload(payload models.SubCategories) *GetSubCategoriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sub categories o k response
func (o *GetSubCategoriesOK) SetPayload(payload models.SubCategories) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSubCategoriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Set("Access-Control-Allow-Origin", "*")
	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.SubCategories, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetSubCategoriesNotFoundCode is the HTTP code returned for type GetSubCategoriesNotFound
const GetSubCategoriesNotFoundCode int = 404

/*GetSubCategoriesNotFound No items found

swagger:response getSubCategoriesNotFound
*/
type GetSubCategoriesNotFound struct {
}

// NewGetSubCategoriesNotFound creates GetSubCategoriesNotFound with default headers values
func NewGetSubCategoriesNotFound() *GetSubCategoriesNotFound {
	return &GetSubCategoriesNotFound{}
}

// WriteResponse to the client
func (o *GetSubCategoriesNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Set("Access-Control-Allow-Origin", "*")
	rw.WriteHeader(404)
}
