// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetSubCategoriesHandlerFunc turns a function with the right signature into a get sub categories handler
type GetSubCategoriesHandlerFunc func(GetSubCategoriesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSubCategoriesHandlerFunc) Handle(params GetSubCategoriesParams) middleware.Responder {
	return fn(params)
}

// GetSubCategoriesHandler interface for that can handle valid get sub categories params
type GetSubCategoriesHandler interface {
	Handle(GetSubCategoriesParams) middleware.Responder
}

// NewGetSubCategories creates a new http.Handler for the get sub categories operation
func NewGetSubCategories(ctx *middleware.Context, handler GetSubCategoriesHandler) *GetSubCategories {
	return &GetSubCategories{Context: ctx, Handler: handler}
}

/*GetSubCategories swagger:route GET /subcategories Subcategories getSubCategories

Get all SubCategories

*/
type GetSubCategories struct {
	Context *middleware.Context
	Handler GetSubCategoriesHandler
}

func (o *GetSubCategories) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetSubCategoriesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
