// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// GetSubCategoriesByCategoryOKCode is the HTTP code returned for type GetSubCategoriesByCategoryOK
const GetSubCategoriesByCategoryOKCode int = 200

/*GetSubCategoriesByCategoryOK Status Ok

swagger:response getSubCategoriesByCategoryOK
*/
type GetSubCategoriesByCategoryOK struct {

	/*
	  In: Body
	*/
	Payload models.SubCategories `json:"body,omitempty"`
}

// NewGetSubCategoriesByCategoryOK creates GetSubCategoriesByCategoryOK with default headers values
func NewGetSubCategoriesByCategoryOK() *GetSubCategoriesByCategoryOK {
	return &GetSubCategoriesByCategoryOK{}
}

// WithPayload adds the payload to the get sub categories by category o k response
func (o *GetSubCategoriesByCategoryOK) WithPayload(payload models.SubCategories) *GetSubCategoriesByCategoryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get sub categories by category o k response
func (o *GetSubCategoriesByCategoryOK) SetPayload(payload models.SubCategories) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSubCategoriesByCategoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Set("Access-Control-Allow-Origin", "*")
	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.SubCategories, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetSubCategoriesByCategoryNotFoundCode is the HTTP code returned for type GetSubCategoriesByCategoryNotFound
const GetSubCategoriesByCategoryNotFoundCode int = 404

/*GetSubCategoriesByCategoryNotFound No items found

swagger:response getSubCategoriesByCategoryNotFound
*/
type GetSubCategoriesByCategoryNotFound struct {
}

// NewGetSubCategoriesByCategoryNotFound creates GetSubCategoriesByCategoryNotFound with default headers values
func NewGetSubCategoriesByCategoryNotFound() *GetSubCategoriesByCategoryNotFound {
	return &GetSubCategoriesByCategoryNotFound{}
}

// WriteResponse to the client
func (o *GetSubCategoriesByCategoryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
	rw.Header().Set("Access-Control-Allow-Origin", "*")
	rw.WriteHeader(404)
}
