// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UpdateSubCategoryHandlerFunc turns a function with the right signature into a update sub category handler
type UpdateSubCategoryHandlerFunc func(UpdateSubCategoryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateSubCategoryHandlerFunc) Handle(params UpdateSubCategoryParams) middleware.Responder {
	return fn(params)
}

// UpdateSubCategoryHandler interface for that can handle valid update sub category params
type UpdateSubCategoryHandler interface {
	Handle(UpdateSubCategoryParams) middleware.Responder
}

// NewUpdateSubCategory creates a new http.Handler for the update sub category operation
func NewUpdateSubCategory(ctx *middleware.Context, handler UpdateSubCategoryHandler) *UpdateSubCategory {
	return &UpdateSubCategory{Context: ctx, Handler: handler}
}

/*UpdateSubCategory swagger:route PUT /subcategories/{id} Subcategories updateSubCategory

Update a specific SubCategory

*/
type UpdateSubCategory struct {
	Context *middleware.Context
	Handler UpdateSubCategoryHandler
}

func (o *UpdateSubCategory) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateSubCategoryParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
