// Code generated by go-swagger; DO NOT EDIT.

package subcategories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/aeckard87/WornOut/models"
)

// UpdateSubCategoryCreatedCode is the HTTP code returned for type UpdateSubCategoryCreated
const UpdateSubCategoryCreatedCode int = 201

/*UpdateSubCategoryCreated SubCategory Updated

swagger:response updateSubCategoryCreated
*/
type UpdateSubCategoryCreated struct {

	/*
	  In: Body
	*/
	Payload *models.SubCategory `json:"body,omitempty"`
}

// NewUpdateSubCategoryCreated creates UpdateSubCategoryCreated with default headers values
func NewUpdateSubCategoryCreated() *UpdateSubCategoryCreated {
	return &UpdateSubCategoryCreated{}
}

// WithPayload adds the payload to the update sub category created response
func (o *UpdateSubCategoryCreated) WithPayload(payload *models.SubCategory) *UpdateSubCategoryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update sub category created response
func (o *UpdateSubCategoryCreated) SetPayload(payload *models.SubCategory) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateSubCategoryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateSubCategoryBadRequestCode is the HTTP code returned for type UpdateSubCategoryBadRequest
const UpdateSubCategoryBadRequestCode int = 400

/*UpdateSubCategoryBadRequest Invalid input

swagger:response updateSubCategoryBadRequest
*/
type UpdateSubCategoryBadRequest struct {
}

// NewUpdateSubCategoryBadRequest creates UpdateSubCategoryBadRequest with default headers values
func NewUpdateSubCategoryBadRequest() *UpdateSubCategoryBadRequest {
	return &UpdateSubCategoryBadRequest{}
}

// WriteResponse to the client
func (o *UpdateSubCategoryBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// UpdateSubCategoryNotFoundCode is the HTTP code returned for type UpdateSubCategoryNotFound
const UpdateSubCategoryNotFoundCode int = 404

/*UpdateSubCategoryNotFound No items found

swagger:response updateSubCategoryNotFound
*/
type UpdateSubCategoryNotFound struct {
}

// NewUpdateSubCategoryNotFound creates UpdateSubCategoryNotFound with default headers values
func NewUpdateSubCategoryNotFound() *UpdateSubCategoryNotFound {
	return &UpdateSubCategoryNotFound{}
}

// WriteResponse to the client
func (o *UpdateSubCategoryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
}
