// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// NewCreateDetailParams creates a new CreateDetailParams object
// with the default values initialized.
func NewCreateDetailParams() *CreateDetailParams {
	var ()
	return &CreateDetailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateDetailParamsWithTimeout creates a new CreateDetailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateDetailParamsWithTimeout(timeout time.Duration) *CreateDetailParams {
	var ()
	return &CreateDetailParams{

		timeout: timeout,
	}
}

// NewCreateDetailParamsWithContext creates a new CreateDetailParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateDetailParamsWithContext(ctx context.Context) *CreateDetailParams {
	var ()
	return &CreateDetailParams{

		Context: ctx,
	}
}

// NewCreateDetailParamsWithHTTPClient creates a new CreateDetailParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateDetailParamsWithHTTPClient(client *http.Client) *CreateDetailParams {
	var ()
	return &CreateDetailParams{
		HTTPClient: client,
	}
}

/*CreateDetailParams contains all the parameters to send to the API endpoint
for the create detail operation typically these are written to a http.Request
*/
type CreateDetailParams struct {

	/*Body
	  Detail that will be created

	*/
	Body *models.Detail

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create detail params
func (o *CreateDetailParams) WithTimeout(timeout time.Duration) *CreateDetailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create detail params
func (o *CreateDetailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create detail params
func (o *CreateDetailParams) WithContext(ctx context.Context) *CreateDetailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create detail params
func (o *CreateDetailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create detail params
func (o *CreateDetailParams) WithHTTPClient(client *http.Client) *CreateDetailParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create detail params
func (o *CreateDetailParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create detail params
func (o *CreateDetailParams) WithBody(body *models.Detail) *CreateDetailParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create detail params
func (o *CreateDetailParams) SetBody(body *models.Detail) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateDetailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body == nil {
		o.Body = new(models.Detail)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
