// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// CreateDetailReader is a Reader for the CreateDetail structure.
type CreateDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateDetailCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateDetailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateDetailCreated creates a CreateDetailCreated with default headers values
func NewCreateDetailCreated() *CreateDetailCreated {
	return &CreateDetailCreated{}
}

/*CreateDetailCreated handles this case with default header values.

Category Created
*/
type CreateDetailCreated struct {
	Payload *models.Detail
}

func (o *CreateDetailCreated) Error() string {
	return fmt.Sprintf("[POST /details][%d] createDetailCreated  %+v", 201, o.Payload)
}

func (o *CreateDetailCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Detail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDetailBadRequest creates a CreateDetailBadRequest with default headers values
func NewCreateDetailBadRequest() *CreateDetailBadRequest {
	return &CreateDetailBadRequest{}
}

/*CreateDetailBadRequest handles this case with default header values.

Invalid input
*/
type CreateDetailBadRequest struct {
}

func (o *CreateDetailBadRequest) Error() string {
	return fmt.Sprintf("[POST /details][%d] createDetailBadRequest ", 400)
}

func (o *CreateDetailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
