// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteDetailReader is a Reader for the DeleteDetail structure.
type DeleteDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteDetailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteDetailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteDetailNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteDetailOK creates a DeleteDetailOK with default headers values
func NewDeleteDetailOK() *DeleteDetailOK {
	return &DeleteDetailOK{}
}

/*DeleteDetailOK handles this case with default header values.

Status Ok
*/
type DeleteDetailOK struct {
}

func (o *DeleteDetailOK) Error() string {
	return fmt.Sprintf("[DELETE /details/{id}][%d] deleteDetailOK ", 200)
}

func (o *DeleteDetailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDetailBadRequest creates a DeleteDetailBadRequest with default headers values
func NewDeleteDetailBadRequest() *DeleteDetailBadRequest {
	return &DeleteDetailBadRequest{}
}

/*DeleteDetailBadRequest handles this case with default header values.

Invalid input
*/
type DeleteDetailBadRequest struct {
}

func (o *DeleteDetailBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /details/{id}][%d] deleteDetailBadRequest ", 400)
}

func (o *DeleteDetailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDetailNotFound creates a DeleteDetailNotFound with default headers values
func NewDeleteDetailNotFound() *DeleteDetailNotFound {
	return &DeleteDetailNotFound{}
}

/*DeleteDetailNotFound handles this case with default header values.

No items found
*/
type DeleteDetailNotFound struct {
}

func (o *DeleteDetailNotFound) Error() string {
	return fmt.Sprintf("[DELETE /details/{id}][%d] deleteDetailNotFound ", 404)
}

func (o *DeleteDetailNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
