// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDetailsParams creates a new GetDetailsParams object
// with the default values initialized.
func NewGetDetailsParams() *GetDetailsParams {

	return &GetDetailsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDetailsParamsWithTimeout creates a new GetDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDetailsParamsWithTimeout(timeout time.Duration) *GetDetailsParams {

	return &GetDetailsParams{

		timeout: timeout,
	}
}

// NewGetDetailsParamsWithContext creates a new GetDetailsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDetailsParamsWithContext(ctx context.Context) *GetDetailsParams {

	return &GetDetailsParams{

		Context: ctx,
	}
}

// NewGetDetailsParamsWithHTTPClient creates a new GetDetailsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetDetailsParamsWithHTTPClient(client *http.Client) *GetDetailsParams {

	return &GetDetailsParams{
		HTTPClient: client,
	}
}

/*GetDetailsParams contains all the parameters to send to the API endpoint
for the get details operation typically these are written to a http.Request
*/
type GetDetailsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get details params
func (o *GetDetailsParams) WithTimeout(timeout time.Duration) *GetDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get details params
func (o *GetDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get details params
func (o *GetDetailsParams) WithContext(ctx context.Context) *GetDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get details params
func (o *GetDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get details params
func (o *GetDetailsParams) WithHTTPClient(client *http.Client) *GetDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get details params
func (o *GetDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
