// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// GetDetailReader is a Reader for the GetDetail structure.
type GetDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDetailOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetDetailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetDetailNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDetailOK creates a GetDetailOK with default headers values
func NewGetDetailOK() *GetDetailOK {
	return &GetDetailOK{}
}

/*GetDetailOK handles this case with default header values.

Status Ok
*/
type GetDetailOK struct {
	Payload *models.Detail
}

func (o *GetDetailOK) Error() string {
	return fmt.Sprintf("[GET /details/{id}][%d] getDetailOK  %+v", 200, o.Payload)
}

func (o *GetDetailOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Detail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDetailBadRequest creates a GetDetailBadRequest with default headers values
func NewGetDetailBadRequest() *GetDetailBadRequest {
	return &GetDetailBadRequest{}
}

/*GetDetailBadRequest handles this case with default header values.

Invalid input
*/
type GetDetailBadRequest struct {
}

func (o *GetDetailBadRequest) Error() string {
	return fmt.Sprintf("[GET /details/{id}][%d] getDetailBadRequest ", 400)
}

func (o *GetDetailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDetailNotFound creates a GetDetailNotFound with default headers values
func NewGetDetailNotFound() *GetDetailNotFound {
	return &GetDetailNotFound{}
}

/*GetDetailNotFound handles this case with default header values.

No items found
*/
type GetDetailNotFound struct {
}

func (o *GetDetailNotFound) Error() string {
	return fmt.Sprintf("[GET /details/{id}][%d] getDetailNotFound ", 404)
}

func (o *GetDetailNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
