// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// GetDetailsReader is a Reader for the GetDetails structure.
type GetDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetDetailsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetDetailsOK creates a GetDetailsOK with default headers values
func NewGetDetailsOK() *GetDetailsOK {
	return &GetDetailsOK{}
}

/*GetDetailsOK handles this case with default header values.

Status Ok
*/
type GetDetailsOK struct {
	Payload models.Details
}

func (o *GetDetailsOK) Error() string {
	return fmt.Sprintf("[GET /details][%d] getDetailsOK  %+v", 200, o.Payload)
}

func (o *GetDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDetailsNotFound creates a GetDetailsNotFound with default headers values
func NewGetDetailsNotFound() *GetDetailsNotFound {
	return &GetDetailsNotFound{}
}

/*GetDetailsNotFound handles this case with default header values.

No items found
*/
type GetDetailsNotFound struct {
}

func (o *GetDetailsNotFound) Error() string {
	return fmt.Sprintf("[GET /details][%d] getDetailsNotFound ", 404)
}

func (o *GetDetailsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
