// Code generated by go-swagger; DO NOT EDIT.

package details

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/aeckard87/WornOut/models"
)

// UpdateDetailReader is a Reader for the UpdateDetail structure.
type UpdateDetailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDetailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewUpdateDetailCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUpdateDetailBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewUpdateDetailNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateDetailCreated creates a UpdateDetailCreated with default headers values
func NewUpdateDetailCreated() *UpdateDetailCreated {
	return &UpdateDetailCreated{}
}

/*UpdateDetailCreated handles this case with default header values.

Detail Updated
*/
type UpdateDetailCreated struct {
	Payload *models.Detail
}

func (o *UpdateDetailCreated) Error() string {
	return fmt.Sprintf("[PUT /details/{id}][%d] updateDetailCreated  %+v", 201, o.Payload)
}

func (o *UpdateDetailCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Detail)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateDetailBadRequest creates a UpdateDetailBadRequest with default headers values
func NewUpdateDetailBadRequest() *UpdateDetailBadRequest {
	return &UpdateDetailBadRequest{}
}

/*UpdateDetailBadRequest handles this case with default header values.

Invalid input
*/
type UpdateDetailBadRequest struct {
}

func (o *UpdateDetailBadRequest) Error() string {
	return fmt.Sprintf("[PUT /details/{id}][%d] updateDetailBadRequest ", 400)
}

func (o *UpdateDetailBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUpdateDetailNotFound creates a UpdateDetailNotFound with default headers values
func NewUpdateDetailNotFound() *UpdateDetailNotFound {
	return &UpdateDetailNotFound{}
}

/*UpdateDetailNotFound handles this case with default header values.

No items found
*/
type UpdateDetailNotFound struct {
}

func (o *UpdateDetailNotFound) Error() string {
	return fmt.Sprintf("[PUT /details/{id}][%d] updateDetailNotFound ", 404)
}

func (o *UpdateDetailNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
